#+TITLE: Årets största högtid
#+AUTHOR: Tamás Szilágyi
#+DATE: 10 september 2015
#+OPTIONS: ^:{} toc:nil num:nil
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [12pt]
#+LATEX_HEADER: \usepackage[a4paper,margin=2.5cm,footskip=1.0cm]{geometry}
#+LATEX_HEADER: \usepackage{baskervald}
#+LATEX_HEADER: \usepackage[swedish]{babel}
#+LATEX_HEADER: \usepackage[parfill]{parskip}

* Vilken är årets största högtid för dig? Varför?

Årets största högtid för mig är dagen när jag för första gången
träffade min fru. Det är dagen som för evigt har förändrat mitt
liv. Jag minns att jag gillade henne omedelbart, och vi blev snabbt
djupt förälskade i varandra. Vi kommer alltid att minnas den dagen på
året, den är mycket speciell för oss båda. Vi träffades på ett kafé en
mulen kväll i slutet av september. Vi pratade bara i ett par minuter
på den dagen, men det var början på en mycket lycklig historia.

* Om du fick göra en helt ny helgdag, vilken dag skulle det då vara? Varför?

Jag vet inte vilken dag det slutligen blir, men det blir ju mitt
första barns födelsedag. Förlossningen är förväntad i mitten av mars.
Det ska bli mycket spännande både för mig och min fru.
