* Ordbok

** Substantiv

bock, en                                goat
böckling, en                            buckling, smoked Baltic herring
dillkronor                              dill / kapor
förberedelse, en                        preparation
haklapp, en                             bib / előke
halm, en                                straw
julgranssaker                           Christmas stuff (hung on the tree)
kamin, en                               stove, heater
kräftor                                 crayfish
kräftskiva, en                          crayfish party
lutfisk, en                             stockfish / szárított tőkehal
löv, ett                                leaf, leaves
pensel, en                              brush
redskap, ett                            tool (also fig.)
ris, ett                                sprigs, twigs / gallyak
rusdryck, en                            alcoholic beverage, intoxicant
sed, en                                 custom, usage, practice
semla, en                               semla, cream bun
skorsten, en                            chimney, funnel, smokestack
slant, en                               coin
stearinljus, ett                        candle
uppståndelse, en                        resurrection, stir
visp, en                                whisk, beater / habverő
ångest, en                              anxiety, fear, dread

** Verb

fattas                                  be missing (short, lacking)
förknippa                               associate
gäller [gällde, gällt]                  pertain to, apply, concern
gömma                                   conceal, hide
rita                                    draw, design
rulla                                   roll
  på                                    trill / trillázik
tigga [tiggde, tiggt, tigg, tigger]     beg

** Adjektiv

galen                                   mad, crazy, wrong

** Fraser

17:25 -- fem i halv sex
17:20 -- tjugo över fem

Jag tycker om kaffe.
Jag tänker på dig.
           tillbaka på min barndom.
Jag tycker att flickan är mycket söt.
Jag tror, men jag är inte säker.

Vilken väg ska jag ta?
börja sig så smått                      ta sin tid
lika gärna som att ...
vara på benen ...
har koll på


* Läxor

** Övningsbok sidan 115: Ordkunskap

a/7. Den svenske kungen har ingen *krona* på huvudet.
b/2. Det fattas några *redskap* här i köket, visp t ex.
c/5. Jag klädde ut mig till Kalle Anka och hade en *mask* för ansiktet.
d/1. Vissa tror att tomten kommer genom *skorstenen*.
e/6. Vi hade massa gammalt skräp i trädgården som vi *brände*. Det blev en stor eld.
f/4. Min hund är galen i skor. Vi måste *gömma* alla så att han inte äter upp dem.
g/3. Mina barn *tiggde* och bad om att få godis så till slut köpte jag en påse åt dem.

** Textbok sidan 145 C: Svara på frågorna

1. Vad hände på lucianatten?

På lucianatten hände många konstiga saker, bland annat kunde djuren
tala och troll och andra figurer som vanligtvis var osynliga blev
synliga.

2. Vad hade Lucia med djävulen att göra?

Man blandade ihop namnen Lucia och Lucifer, alltså djävulen, så många
var lite rädda för henne.

3. När började man fira lucia som vi gör i dag?

Det moderna offentliga luciafirandet och sångerna är ett
1900-talsfenomen. Det var Stockholmstidningen som år 1927 ordnade ett
luciatåg genom stan.

4. Berätta om Luciasången.

Luciasångens melodi är tagen från en italiensk visa. Texten skrevs
under 1900-talet, men författaren använde många gamla ord så att
sången skulle verka äldre. Sången börjar: "Natten går tunga fjät runt
gård och stuva". Fjät betyder steg och stuva betyder stuga.

5. Vad är häxor för något och vad trodde man att de gjorde på påsken?

Häxor var kvinnor som kunde trolla och som man trodde samarbetade med
djävulen.

6. Vad hände med kvinnor som man trodde var häxor på 1600-talet?

De anklagades för att vara häxor och dödades genom att brännas på bål,
ofta efter hemsk tortyr.

7. Vad gjorde påskkärringarna på 1800-talet?

De klädde ut sig till häxor med skrämmande masker och en kvast. De
kunde slänga ner stenar i skorstenen eller lägga en glasskiva över den
så att huset blev fullt av rök.

8. Vilka två "släktingar" har jultomten?

Den ena är den snälla tomten från Tyskland som är lång, vitskäggig och
rödklädd och den andra är den svenska urtomten.

9. Berätta om den svenska urtomten.

Den svenska urtomten är mycket liten och gråklädd för att inte väcka
uppmärksamhet. Han bor på bondgårdar hos djuren och hjälper till med
det mesta som behöver skötas på en bondgård.

10. Vad handlar dikten "Tomten" om?

Den handlar om den svenska urtomten och hur han nattetid kontrollerar
att djur och människor mår bra på gården där han bor. Han funderar
också på varifrån människorna kommer.

** Meningar med partikelverb

släppa in: Mina skor släpper in vatten. Mina skor läcker.
           Släppa in hunden på kvällen!
           Jag lät mina gäster komma in.
           Det knackade på dörren och jag släpte in min granne för
             han hade låst sig ute.
sätta på: Sätt på teven, jag vill titta på rapport!
stänga av: När man åker flygplan måste man stänga av mobiltelefonen.
ser ut: Varifrån kommer du? Du ser fruktansvärt trött ut!
blanda ihop: Man blandar ofta ihop namnen som låter likadana.

dyka upp
slänga ner
gömma undan
hjälper till
ställer ut
kommer in
gå iväg
gå ut
klä om
fundera på
** Övningsbok sidor 122-124: Sortera meningarna

A
1. Var det i Sverige ni träffades?
2. Vem är det som har ritat ert hus?
3. Är det du som inte har diskat din kopp?
4. Var det 1998 ni gifte er?
5. Varför är det ingen som har gjort läxan?

B
1. Det var jag som läste en bok om Sveriges historia i vardagsrummet i går.
2. Det var en bok om Sveriges historia som jag läste i vardagsrummet i går.
3. Det var i vardagsrummet som jag läste en bok om Sveriges historia i går.
4. Det var i går som jag läste en bok om Sveriges historia i vardagsrummet.
5. Vem är det som inte har låst dörren efter sig?
6. Är det någon som har låst ytterdörren?

C
1. - Vem är det som använde min dator i går?
   - Det var inte jag som gjorde det.
2. - Inte? Var det inte du som satt på min plats när jag kom från lunchen?
   - Jo, men det var inte i går som jag satt där.
3. - Nähä. När var det som du satt där då?
   - Det var i förrgår som jag satt vid din dator.
