* Ordbok

** Substantiv

bock, en                                goat
dillkronor                              dill / kapor
förberedelse, en                        preparation
haklapp, en                             bib / előke
halm, en                                straw
julgranssaker                           Christmas stuff (hung on the tree)
kamin, en                               stove, heater
kräftor                                 crayfish
kräftskiva, en                          crayfish party
lutfisk, en                             stockfish / szárított tőkehal
löv, ett                                leaf, leaves
pensel, en                              brush
redskap, ett                            tool (also fig.)
ris, ett                                sprigs, twigs / gallyak
rusdryck, en                            alcoholic beverage, intoxicant
semla, en                               semla, cream bun
skorsten, en                            chimney, funnel, smokestack
slant, en                               coin
stearinljus, ett                        candle
uppståndelse, en                        resurrection, stir
visp, en                                whisk, beater / habverő

** Verb

fattas                                  be missing (short, lacking)
förknippa                               associate
gäller [gällde, gällt]                  pertain to, apply, concern
gömma                                   conceal, hide
rita                                    draw, design
rulla                                   roll
  på                                    trill / trillázik
tigga [tiggde, tiggt, tigg, tigger]     beg

** Adjektiv

galen                                   mad, crazy, wrong

** Fraser

17:25 -- fem i halv sex
17:20 -- tjugo över fem

Jag tycker om kaffe.
Jag tänker på dig.
           tillbaka på min barndom.
Jag tycker att flickan är mycket söt.
Jag tror, men jag är inte säker.

Vilken väg ska jag ta?
börja sig så smått                      ta sin tid
lika gärna som att ...
vara på benen ...
har koll på


* Läxor

** Läxa 1: Övningsbok p.115: Ordkunskap

a/7. Den svenske kungen har ingen *krona* på huvudet.
b/2. Det fattas några *redskap* här i köket, visp t ex.
c/5. Jag klädde ut mig till Kalle Anka och hade en *mask* för ansiktet.
d/1. Vissa tror att tomten kommer genom *skorstenen*.
e/6. Vi hade massa gammalt skräp i trädgården som vi *brände*. Det blev en stor eld.
f/4. Min hund är galen i skor. Vi måste *gömma* alla så att han inte äter upp dem.
g/3. Mina barn *tiggde* och bad om att få godis så till slut köpte jag en påse åt dem.
