* Ordbok

** Substantiv

bock, en                                goat
förberedelse, en                        preparation
halm, en                                straw
julgranssaker                           Christmas stuff (hung on the tree)
kamin, en                               stove, heater
lutfisk, en                             stockfish / szárított tőkehal
löv, ett                                leaf, leaves
pensel, en                              brush
redskap, ett                            tool (also fig.)
ris, ett                                sprigs, twigs / gallyak
skorsten, en                            chimney, funnel, smokestack
visp, en                                whisk, beater / habverő

** Verb

fattas                                  be missing (short, lacking)
gömma                                   conceal, hide
tigga [tiggde, tiggt, tigg, tigger]     beg

** Adjektiv

galen                                   mad, crazy, wrong


* Läxor

** Läxa 1: Övningsbok p.115: Ordkunskap

a/7. Den svenske kungen har ingen *krona* på huvudet.
b/2. Det fattas några *redskap* här i köket, visp t ex.
c/5. Jag klädde ut mig till Kalle Anka och hade en *mask* för ansiktet.
d/1. Vissa tror att tomten kommer genom *skorstenen*.
e/6. Vi hade massa gammalt skräp i trädgården som vi *brände*. Det blev en stor eld.
f/4. Min hund är galen i skor. Vi måste *gömma* alla så att han inte äter upp dem.
g/3. Mina barn *tiggde* och bad om att få godis så till slut köpte jag en påse åt dem.
