* svt2 Aktuell, 21:23-21:30

Det var en bombexplosion i måndags i Bangkok, Thailand.
Minst 20 människor dog och fler än 100 skadades.
Bomben sprängdes nära en tågstation och en tempel i ett populärt område.

Thailand är en turistparadis, men också ett land med stora spänningar.
Det har varit politiska bråk i Thailand i många år tidigare.
Men hittils har det varit lugn och säkerhet i landet.

Man vet inte vilken terrorgrupp är skyldig. Det kan vara Al Kaida,
Islamiska Staten, eller kanske separatisten i norra delen av landet,
eller någon muslimsk grupp från södra Thailand?

Vi vet alltså inte varför det hände.
Idag placerade man blommor och samlat till minne av de som har dödades.


- övergripande nationella konflikt den senaste årgripandet
- motståndare, våld på gatorna
- militärstyre
- Al Kaida, Islamiska Staten, separatisten?
- ingen säger att de ligger bakom attak.
- otroligt att orsaka fler explosioner, för att folket återhämta sig
- statskuppen
- man spekulerar att det är en attack med internationella bakgrund.
- mänga människor ligger skadad efter explosion
