#+TITLE: Sigurd drakdödaren
#+AUTHOR: Tamás Szilágyi
#+DATE: 9 december 2015
#+OPTIONS: ^:{} toc:nil num:nil
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [12pt]
#+LATEX_HEADER: \usepackage[a4paper,margin=2.5cm,footskip=1.0cm]{geometry}
#+LATEX_HEADER: \usepackage{baskervald}
#+LATEX_HEADER: \usepackage[swedish]{babel}
#+LATEX_HEADER: \usepackage[parfill]{parskip}

Det fanns ett stort hus där en familj bodde. Det var vanligt att ha
fester där. En gång kom en mystisk man som ingen kände. Han hade med
sig ett svärd. I mitten av huset stod ett stort träd. Mannen gick
fram till trädet och högg in svärdet i det. Sedan lämnade han utan att
berätta vem han var.

Alla starka män försökte dra ut svärdet, men ingen lyckades.  Men
Sigmund, som var yngste sonen i familjen, kunde göra det lätt. Han
växte upp och blev en krigare, och använde svärdet i många strider och
hade framgång med det. Men den okända mannen, som tog med sig svärdet,
dök upp igen. Han bröt Sigmunds svärd i tre delar och försvann
igen. Då blev Sigmund sårbar. Han skadades allvarligt och förlorade
striden. Men innan han dog, bad han sin fru att förvara svärdets
delar.

Hans fru födde en son, som hette Sigurd och som blev en stark ung man.
Han lärde sig att kriga från hans lärare som hette Regin. Regin ville
att Sigurd skulle döda en drake och ta drakens guldskatt för honom.
Han ville också döda Sigurd efteråt, men han höll det hemligt.

Sigurd lagade svärdet som låg i delarna, därför att han skulle döda
draken med det svärdet. Han gick till drakens hem och väntade tills
den kom ute. Då hoppade Sigurd fram och dödade draken med sitt svärd.
Drakens blod rann ut och Sigurd fick några droppar av det på sin
hand. Blodet brände hans kropp, så han stoppade fingret i munnen. Men
drakens blod var magisk: efter han smakade det, kunde han förstå
fåglarnas röst.  En fågel berättade för honom att Regin skulle döda
honom efter han återvände med guldskatten. Då tog Sigurd drakens guld
och gick hem, där han dödade Regin och behöll skatten för sig.
