Anteckningar om Svenska Utifrån

http://folkets-lexikon.csc.kth.se/folkets/folkets.en.html

http://lexin.nada.kth.se/lang/trio/sv/index.htm

http://api.sr.se/api/rss/pod/4019
Programmet som förklarar nyheterna på ett enklare sätt.


* Ordbok

** SUBSTANTIV - NOUNS - FŐNEVEK

kort (ett)                              card
påstående (ett)                         statement, assertion
skådespelare (en)                       actor/actress
bok (en)                                book / könyv
bänk (en)                               bench / pad
dörr (en)                               door / ajtó
fönster (ett)                           window / ablak
penna (en)                              pen / toll
suddgummi (ett)                         eraser / radírgumi
vägg (en)                               wall / fal
papper (ett)                            paper / papír
väska (en)                              bag / táska
bord (ett)                              table / asztal
stol (en)                               chair / szék
tolk (en)                               interpreter / tolmács?
katt (en)                               cat / macska
filmrulle (en)                          roll of film / filmtekercs
kamera (en)                             camera / fényképezőgép
batong (en)                             baton / gumibot
skruvmejsel (en)                        screwdriver / csavarhúzó
pistol (en)                             pistol / pisztoly
block (ett)                             block /  blokk (jegyzettömb)
såg (en)                                saw / fűrész
blixt (en)                              lightning, flashlight / villám, vaku
hammare (en)                            hammer / kalapács
stativ (ett)                            tripod/stand / (fotó)állvány
måttband (ett)                          tape measure / mérőszalag
fågel (en)                              bird / madár
hund (en)                               dog / kutya
siames (en)                             siamese cat / sziámi macska
skata (en)                              magpie / szarka
förslag (ett)                           proposal / javaslat
helg (en)                               holiday, weekend / ünnep, hétvége
framtid (en)                            future / jövő
pärm (en)                               folder, file / mappa, iratgyűjtő
betydelse (en)                          meaning, sense
frimärke (ett)                          stamp / bélyeg
mynt (ett)                              coin / érme
semester(en)                            holiday, vacation / szabadság
medborgare (en)  [mé:d-borjare]         citizen / polgár
rulltrappa -an -or                      escalator / felvonó
timme (en)                              hour (also lesson) / óra (tanóra is)
tur (en)                                luck / szerencse
medlem (en)                             member, membership / tag, tagság
pass (ett)                              passport / útlevél
arbets|tillstånd (ett)                  work permit / munkavállalási engedély
dygn (ett)                              day (24h period) / nap (24 óra)
yta (en)                                space, area, surface
område (ett)                            area / terület
drottning (en)                          queen / királynő
svägerska (en), svägerskor[szve:goskur] sister-in-law / sógornő
svärfar, svärmor                        father-in-law, mother-in-law / após, anyós
par (ett)                               pair / pár
släkt (en)                              family, relatives, relations / rokonság
släkting (en)                           relative, kindred, relation / rokon
ätt (en)                                family / család
ursprung (ett)                          origin / eredet
fiol (en)                               violin / hegedű
nyckelharpa (?)                         key harp (traditional swedish instrument)
ämne (ett)                              material, matter, subject / anyag, tárgy
mejeri (ett)                            dairy / tejtermék
korg (en)  [korj]                       basket / kosár
apelsin (en)                            orange / narancs
torsk (en) [tosk]                       cod / tőkehal
burk (en)                               tin (can [US]), pot, jar / doboz (fém), üveg, korsó
päron (ett)                             pear / körte
gurka (en)                              cucumber / uborka
ägg (ett)                               egg / tojás
limpa (en)                              loaf / cipó, vekni
räkor                                   shrimp(s) / apró tengeri rákok
fläsk (ett)                             pork / disznóhús
fläskkotlett, -er                       porkchop / sertésszelet
ärt (en)                                pea / borsó
flinga (en), -or                        flake, cornflakes / (kukorica)pehely
glass (en)                              ice cream / fagylalt
ost (en)                                cheese / sajt
skinka (en)                             buttock, ham / fenék, sonka
avokado (en)                            avocado / avokádó
hekto (ett)                             hectogram, 100g / 10 deka
påse (en)                               bag / szatyor
ask (en)                                packet, box / csomag, doboz
bägare (en)                             goblet, cup, mug / pohár, bögre
hjul (ett)                              wheel / kerék
kust (en)                               coast / (tenger)part
vagn (en)                               vehicle / jármű
husvagn                                 caravan / lakóautó
plats (en)                              place, room / (férő)hely
spis (en)                               fireplace, stove, cooker / tűzhely
ugn (en)                                oven / sütő
kylskåp (ett) [síl:szkóp]               refrigerator / hűtőszekrény
diskbänk (en)                           kitchen-sink / mosogató
tak (ett)                               roof, ceiling / plafon, mennyezet
gardin (en)                             curtain, drapery / függöny, drapéria
brandsläckare                           fire extinguisher / tűzoltókészülék
kärring (en)                            old woman [pejorative] / nyanya, banya
korv (en)                               sausage / kolbász, virsli, szafaládé
pannkaka (en)                           pancake / palacsinta
slag (ett)                              category, type, kind, class, species, sort
rätt (en)                               course, dish / fogás
varmrätt                                főtt étel, melegétel
tallrik (en)                            plate / tányér
gröt (en)                               porridge / zabkása
makaroner                               macaroni / makaróni
skiva (en)                              plate, board, slab, slice, disc, disk[US]
måltid                                  meal
skivstång (en)                          barbell / súlyzó
oväsen (ett)                            noise / zaj
gitarr (en)                             guitar / gitár
stereo (en)                             stereo / magnó, hifi-torony
högtalare (en)                          loudspeaker / hangfal, hangszóró
dator (en)                              computer / számítógép
lampa (en)  [bords~, tak~, golv~]       lamp / lámpa
spegel (en)                             mirror / tükör
affisch (en)                            poster, placard / poszter, plakát
fåtölj (en)                             armchair / fotel
kamrat (en)                             friend, comrade, companion
golv (ett)                              floor / padló
hylla (en)                              shelf / polc
uttryck (ett) [űttrükk]                 expression / kifejezés
förteckning (en)                        list, register / lista, jegyzék
innehållsförteckning                    table of contents / tartalomjegyzék
snickare                                carpenter / asztalos
uppgift (en) [uppjift]                  task, duty / feladat
tavla (en)                              picture, painting / kép, festmény
stjärna (en) [_Härna]                   star [also figuratively] / csillag, sztár
sällskap (ett) [szellszka:p]            company / cég, társaság
jordbruk (ett) [júrdbrük]               agriculture, farm / mezőgazdaság, gazdaság
genomsnitt (ett)                        average / átlag
åker (en) åkern, åkrar                  arable land, field / szántóföld, mező
äng (en) ängen, ängar                   meadow / rét, legelő
vete (ett)                              wheat / búza
råg (en)                                rye / rozs
raps (en)                               rape / repce
ko (en)                                 cow / tehén
svin (ett)                              swine, pig / sertés, disznó
får (ett)                               sheep / juh, birka
höns (pl.), hönsen                      poultry / tyúk, baromfi
kyckling (en)                           chicken / csibe, csirke
ull (en)                                wool / gyapjú
lån (ett)                               loan / kölcsön
uppmärksamhet (en)                      attention / figyelem
kiosk (en) [soszk]                      kiosk, kioszk
guldsmed (en)                           goldsmith / aranyműves
halsband (ett)                          necklace / nyaklánc
fest (en)                               party / buli
pärla (en)                              pearl / gyöngy
örhänge (ett)                           earring / fülbevaló
brosch (en)                             brooch / bross, melltű
hårnål (en)                             hairpin / hajtű
hårnålskurva (en)                       hairpin bend / hajtűkanyar
nyckel (en)                             key / kulcs
deltagare (en)                          participant / résztvevő
landshövding (en)                       country governor / tartományfőnök
läxa (en)                               lesson, homework / lecke, házi feladat
kedja (en)                              chain / sorozat, láncolat
varuhuskedja [va:rühűsz-sédja]          áruházlánc
hantverk (ett)                          craft / (kézmű)ipar, kisipar, mesterség
tyg (ett, = v. -er)                     material, fabric / szövet, kelme, anyag
besök (ett)   [på besök]                visit, stay / látogatás  [látogatóba]
företag (ett)                           company, business, enterprise / cég, vállalat, vállalkozás
dikt (en)                               fabrication, poem, fiction, poetry / kitalálmány, vers, költemény, költés
stuga (en)                              cottage, cabin, hut / kunyhó, házikó
fjäll (ett)                             mountain / hegy, magashegység, havasok
byråkrat (en)                           bureaucrat / bürokrata
tjänsteman, tjänstemän                  salaried worker, white collar / tisztviselő, hivatalnok, alkalmazott
samhälle (ett)                          village, place, community / falu, közösség, társadalom
välfärd (en)                            welfare / jólét
tillgång (en)                           access, supply / hozzáférés, hozzájutás, ellátottság
naturtillgång                           natural asset / természeti erőforrás
älv (en)                                river / folyó
böna (en)                               bean / bab
midsommar (en, -somrar)                 midsummer / nyárközép, nyári napforduló (jún.21)
valborgsmässoafton                      Walpurgis night / tavaszünnep, ápr.30 (május 1. előestéje)
riksdag (en)                            Parliament / parlament
regering (en)                           government / kormány
demokrati (en)                          democracy / demokrácia
dräkt (en)                              costume, dress / ruha, öltözet, viselet
fall (ett)                              fall, case / esés, eset
spelman (en, spelmän)                   folk musician / népi zenész, hegedűs
strumpa (en)                            stocking, sock / harisnya, zokni
byxa (en) -> byxor (plural)             pants, trousers / nadrág
jacka (en)                              jacket / kabát, zeke, ~blézer
hatt (en)                               hat / kalap
väst (en)                               vest / mellény
skjorta (en)                            shirt / (férfi)ing
knä (ett)                               knee / térd
tofs (en)                               tuft / bojt, rojt
sjal (en)                               scarf / sál, (fej)kendő
axel (en, axlar)                        shoulder / váll
kjol (en)                               skirt / szoknya
fot (en, fötter)                        foot / lábfej
förkläde (ett)                          apron / kötény
sko (en)  [träsko]                      shoe / cipő  [fapapucs]
öga (ett, ögon)                         eye / szem
sula (en)                               sole / (cipő)sarok
köp (ett)                               purchase / vásárlás
  till|ge|få på köpet                     a bolt ráadása/bónusza/ajándéka a vásárlás tárgyán felül
sanning (en)                            truth, veracity / igazság, valóság
sömn (en)   [gå i sömnen]               sleep / alvás   [walk in one's sleep]
orm (en)                                snake / kígyó
elefant (en)                            elephant / elefánt
lejon (ett)                             lion / oroszlán
sebra (en)                              zebra / zebra
hane (en)                               male [animal] / hím [állat]
hona (en)                               female [animal] / nőstény [állat]
kalv (en)                               calf / borjú (ált.: állat kölyke)
varg (en)                               wolf / farkas
björn (en)                              bear / medve
järv (en)                               wolverine / torkos borz, rozsomák
älg (en)                                moose / jávorszarvas
lodjur (ett)                            lynx / hiúz
stam (en)                               root, trunk / tő, gyökér [szótő is]
vitlök (en)                             garlic / fokhagyma
bastu (en) [Bada bastu!]                sauna / szauna [Take a sauna!]
råd (ett)                               advice, council / tanács [testület is]
tur (en)                                trip / utazás, kirándulás
säkerhetsbält (ett)                     safety belt / biztonsági öv
näsa (en)                               nose / orr
mun (en [munnen])                       mouth / száj
tå (en)                                 toe / lábujj
rygg (en)                               back / hát [dolgok hátsó oldala is]
bröst (ett)                             chest, breast / mellkas, mell
nacke (en)                              neck / nyak
haka (en)                               chin / áll
mage (en)                               stomach / gyomor
ben (ett)                               leg / láb
panna (en)                              forehead / homlok
öra (ett), öron, öronen                 ear / fül
rörelse (en)                            motion, movement / mozgás, mozdulat
tält (ett)                              tent / sátor
plåster (ett)                           band-aid, plaster / (seb)tapasz
skärp (ett)                             belt / öv
handduk (en)                            towel / törülköző
portmonnä (en)                          purse / erszény, pénztárca
schema (ett)                            timetable, diagram, scheme, schedule / minta, vázlat, beosztás, terv, séma
barnpassning (en)                       child-minding / gyerekgondozás
lön (en)                                wage, salary / munkabér, munkadíj, fizetés
kunskap (en)                            knowledge / tudás, ismeret
leende (ett)                            smile / mosoly
hjärna (en)                             brain / agy(velő), átv.: fej, koponya, okos ember
farbror (en)                            (fraternal) uncle / (apai) nagybácsi
faster (en)                             (fraternal) aunt / (apai) nagynéni
morbror (en)                            (maternal) uncle / (anyai) nagybácsi
moster (en)                             (maternal) aunt / (anyai) nagynéni
försäkringsbolag (ett)                  insurance company / biztosító(társaság)
fängelse (ett)                          prison, jail / börtön
dagis (ett)                             day nursery, kindergarten / óvoda
advokat (en)                            counsel, attorney, lawyer, solicitor / ügyvéd, szószóló, védő
radhus (ett)                            row house / sorház
änka (en)                               widow / özvegy
glasbruk (ett)                          glassworks / üveggyár
skål (en)                               bowl, basin / csésze, tálka
pension (en)                            pension / nyugdíj
bidrag (ett)                            allowance, benefit / járulék, segély
lov (ett)                               holiday, vacation / szünet, szünidő, vakáció
monteringshus (ett)                     prefabricated house / készház
snickeri (ett); snickerifabrik (en)     joinery, carpentry / asztalosműhely, asztalosüzem
affärsidé (en)                          business concept / üzleti koncepció
inredning (en)                          equipment, furnishing / berendezés, bútorozás
  heminredning                          home furnishing / lakberendezés
vykort (ett)                            postcard / levelezőlap, képeslap
rast (en)                               pause, break / szünet, pihenő
kompis (en)                             buddy, mate [informal] / pajtás, cimbora [hétközn.]
flöjt (en)                              flute / fuvola
å (en: ån, åar)                         small river, stream / folyócska, patak
ö (en: ön, öar)                         island / sziget
strand (en, stränder)                   beach, shore / part
berättelse (en)                         tale, narrative, story / elbeszélés, beszámoló, történet
kastrull (en)                           saucepan / lábas, serpenyő
sömmerska (en)                          dressmaker, needlewoman, sewer / varrónő, szabónő
verkstad (en)                           workshop / műhely, üzem, gyár
fack (ett)                              union [inf.], profession, trade / szakszervezet [inf.], szakma, mesterség
nykterhet (en)                          sobriety, soberness / józanság, mértékletesség, absztinencia
nykterhetsrörelse (en)                  temperance movement / antialkoholista mozgalom
biträde (ett)                           assistant, shop assistant / eladó, alkalmazott, segéd, kisegítő
hembiträde (ett)                        maid / szobalány, háztartási alkalmazott
ordförande (en)                         chairman / elnök
verkstadsklubb (en)                     workplace union / munkahelyi szakszervezet
förening (en)                           society, association / társaság, egyesület, szövetség
konditori (ett)                         café, patisserie / kávézó, cukrászda
trottoar (en)                           pavement / járda
tjej (en)                               girl [inf.] / csaj
kille (en)                              fellow, guy, bloke [inf.] / csávó, pasi, srác, fickó, legény
sand (en)                               sand / homok
veckopeng (en)                          weekly pocket money / heti zsebpénz
försvar (ett)                           defence, defense[US] / védelem
  totalförsvar                            overall defence
plikt (en)                              duty / szolgálat
  totalförsvarsplikt                      overall defence duty / általános védelmi szolgálat
värnplikt                               compulsory military service / sorkatonai szolgálat
reserv (en)                             reserve / tartalék
tjänst (en)                             job, post, duty, service / állás, tisztség, szolgálat, hivatal
[militär]tjänstgöring                   [military] service / [sorkatonai] szolgálat
utbildning (en)                         education, training / kiképzés, kiművelés, iskolázás
sökande (en)                            applicant / jelentkező
soldat (en)                             soldier / katona
stridsvagn (en)                         tank / tank
tillägg (ett)                           addition, supplement / kiegészítés, pótlás, toldalék, utóirat, pótlék, felár, pótdíj
utryckning (en)                         discharge / kivonulás, leszerelés
skräck (en)                             terror, horror, dread, fright / ijedtség, rémület, félelem
pluton (en)                             platoon / szakasz
befäl (ett)                             (person in) command, officer(s) / parancsnok(ság), vezénylő(k), elöljáró(k), tiszt(ek)
utmaning (en)                           challenge / kihívás
erfarenhet (en)                         experience / tapasztalat, jártasság, ügyesség
logement (ett)                          barracks / legénységi szoba, lakóhelyiség
köttfärs (en)                           ground meat / darált/vagdalt hús, fasírozott
parti (ett)                             party / párt
val (ett)                               choice, election / (ki)választás, alternatíva
utlänning (en)                          foreigner, alien / külföldi (ember), idegen állampolgár
kammare (en, kamrar, kamrarna)          chamber (of parliament) / kamara, (parlamenti) ház
jämlikhet (en)                          equality / egyenlőség
samling (en)                            gathering, collection, assembly / (össze)gyűjtés, gyülekezés, tömörülés, gyűjtemény, csoportosulás, tömeg
anhängare (en)                          follower, supporter / követő, támogató
marknad (en)                            market / piac
ägande (ett)                            ownership, owning / tulajdon, saját
äganderätt (en)                         right of possession / tulajdonjog
klassamhälle (ett)                      class society / osztálytársadalom
förbund (ett)                           association, union, society / szövetség
landsbygd (ett)                         countryside / vidék, falu
näringsliv (ett)                        trade/industry, business world / üzleti élet
jämställdhet (en)                       gender equality, equal opportunities / egyenjogúság. egyenlő esélyek
kärnkraft (en)                          nuclear power / atomenergia
föremål (ett)                           thing, object, article / tárgy, téma
likgiltighet (en)                       indifference / közömbösség, érzéketlenség
talang (en)                             talent / tehetség
krig (ett)                              war / háború
fred (en)                               peace / béke
maskros (en)                            dandelion / pitypang
stämning (en)                           feeling, mood, atmosphere / hangulat, kedv, lelkiállapot
ögonkast (ett)                          glance, look / pillantás, tekintet
sammanträde (ett)                       conference, meeting / megbeszélés, értekezlet, ülés
ärende (ett)                            errand, commission, matter / ügy, dolog, megbízás, kérelem
ved (en)                                wood / tűzifa
vedspis (en)                            woodstove / fatüzelésű tűzhely
matsäck (en)                            packed lunch / útravaló, tarisznya, kenyérzsák
sågverk (ett)                           sawmill / fűrésztelep, -malom
beställning (en)                        booking, reservation / (meg)rendelés, foglalás
mellanmål (ett)                         snack / uzsonna, tízórai, falatozás
psalm (en)                              psalm / zsoltár
sill (en)                               herring / hering
rotmos (ett)                            mashed turnips / karórépapüré
värk (en)                               ache / fájdalom, fájás
terapi (en)                             therapy / terápia
förbindelse (en)                        relations, connection / összeköttetés, kapcsolat, csatlakozás
organ (ett)                             organ / szerv, orgánum, eszköz
kropp (en)                              body, trunk / test, törzs
häl (en)                                heel / sarok
tarm (en)                               intestine / bél
lever (en)                              liver / máj
hjärta (ett)                            heart / szív
njure (en)                              kidney / vese
stjärt (en)                             tail, backside, behind, bottom / farok, hátsó, ülep, fenék, far, popsi
huvud (ett)                             head / fej, fő, értelem, ész
arm (en)                                arm / kar
armbåge (en)                            elbow / könyök
hand (en)                               hand / kéz
hår (ett)                               hair / haj
kind (en)                               cheek / arc
midja (en)                              waist / derék
finger (-ret)                           finger / ujj
lår (ett)                               thigh / comb
vad (en)                                calf / lábikra, vádli

** VERB - VERBS - IGÉK

heta [heter, hette]                     be called/named / hívják, nevezik vkinek/vminek
tala                                    speak (language) / beszél (nyelvet)
bo                                      live (somewhere) / él (lakik)
följa                                   follow, accompany, comply / követ
undervisa                               teach / tanít
lära                                    teach / tanít
tro                                     believe / hisz
stava                                   spell / betűz
dela                                    cut up, split up, divide, share / feloszt, megoszt
  dela ut                               give away, dispense / kioszt, osztogat
somna                                   fall asleep / elalszik
börja                                   begin / kezd(ődik)
vakna                                   wake / ébred
sluta                                   stop, finish / abbahagy, lezár
åka [åker]                              go, ride / megy, utazik
behöva (behöver)                        want, need, require
vanka                                   saunter / őgyeleg
stunda                                  approach, draw near / közeleg
diska                                   wash the dishes / mosogat
tvätta                                  wash (chothes) / mos
bada                                    bath / fürdik
  bada bastu                              szaunázik
sy                                      sew / varr
  sy om                                   varrással átalakít, átvarr, újra megvarr
sticka                                  knit / köt
väva                                    weave / sző
redovisa                                show, present / bemutat
trivas                                  enjoy, get on [well], thrive
brädsegla                               windsurf, sailboard
dammsuga (dammsuger)                    to vacuum clean / porszívózik
städa                                   clean, tidy up / takarít, rendet rak
stryka (stryker, strök)                 iron, rub, stroke / vasal, (meg- v. végig)simít, simogat, dörzsöl
snickra (snickrar)                      do carpentry / asztalosmunkát végez, barkácsol
måla                                    paint / fest
betala                                  pay / (ki)fizet
laga (lagar)                            make, repair / csinál, javít
få                                      receive, get / kap, szerez
lysa (lyser)                            shine / ragyog
bero (beror) på                         depend on, be due to / függ tőle, múlik rajta
flyta (flyter)                          flow / folyik
använda                                 employ, use, carry, utilize, wear / használ, alkalmaz
tillhöra (tillhör)                      belong / tartozik
förändra                                change / (meg)változik
slarva                                  be careless (negligent), neglect / elhanyagol, nem figyel rá
hoppa över                              omit, leave out / kihagy, elhagy
ställa                                  set, put
ställa in                               adjust, setting   (i stället -- in/as adjustment)
brer (breda)                            spread / megken (kenyeret)
bestå av/i                              contain, consist of, be composed (made up) of
parkera                                 park / leparkol
bära                                    carry, wear
koppla                                  connect, [informal:] catch on
koppla av                               relax
hälsa [på någon]                        greet, welcome sy / köszön(t) vkit/vkinek
odla                                    cultivate (land) / művel (földet)
äga (äger)                              own / birtokol
räcka (räcker)                          pass, hold out, reach, be enough / elér, kitart, elegendő
ge (ger)                                give (also fig.: present, produce) / ad (átvitt értelemben is)
leta efter ...                          look for ... / keres vmit
fungera                                 function / működik, szerepet betölt
ta emot                                 receive, accept / fogad (pl. látogatót)
skaka [skakar ngn hand med X]           shake [shake hands with X]
önska                                   wish, desire, want / kíván, óhajt, kér
önska välkommen                         welcome / üdvözöl
krama                                   hug, squeeze / szorít, (meg/át)ölel
buga                                    bow / meghajol
kyssa [kysser] [süsszer]                kiss / (kezet) csókol
dunka ngn i ryggen                      pound sy on the back / megveregeti a vállát
komma ihåg ngn                          recall/remember sy / emlékszik valakire
låta [lät]                              sound / hangzik
sakna                                   miss / hiányzik (neki valaki)
skicka                                  send, forward / küld, továbbít
skälla [skäller]                        yelp, scold / megszid, gyaláz, pocskondiáz
gilla [gillar]                          approve, like / helyesel, elismer, jóváhagy, jónak tart
bläddra [bläddrar]                      browse / lapozgat, böngészik
ljuga [ljuger]                          lie / hazudik
bjuda [bjuder]                          invite, offer, ask / meghív, kínál, ad
bjuda på middag                         invite to dinner / meghív vacsorára
reta                                    irritate, tease / irritál, zavar, bosszant
gissa                                   suppose, guess / ki- v. eltalál, találgat, megfejt
klä  [Klär du i blått?]                 dress / öltözik  [Do you dress in blue?]
vila                                    rest / pihen
gråta                                   cry, weep / sír, megsirat
spänna                                  tense, draw / (meg)feszít, meghúz, (be)fog, becsatol [pl. bizt.övet]
bromsa                                  brake, apply the brake [also fig.] / fékez, behúzza a féket
stanna                                  stop / megáll, áll, megakad, megszakad
svänga                                  take a turn / kanyarodik, befordul
fortsätta                               continue, go on, carry on / folytat, vmit tovább csinál
vissla                                  whistle / sípol, fütyül
hosta                                   cough / köhög
knacka                                  knock / kopog(tat)
vinka                                   wave / int, integet
tralla                                  sing, warble / dúdolgat, dudorászik
applådera                               applaud, clap / (meg)tapsol
stå                                     stand / áll
räta                                    straighten / kiegyenesít, kinyújt
böja [böj!]                             bow, curve, bend / hajol, hajlít, görbít
klappa                                  clap, pat, pet / tapsol, megvereget, paskol, kopog
lägga [lade]                            put, place, set, lay / fektet, helyez, tesz, rak
knäppa                                  snap, click / csettint, pattint
rynka                                   wrinkle / ráncol, redőz
vifta                                   wave / integet, legyez
hoppa jämfota                           jump with both legs / páros lábbal ugrik
skaffa                                  get, obtain, get hold of / szerez, szert tesz, hoz(at)
stämma                                  agree, correspond, tune, tally / egyezik, stimmel, összhangban van
klara                                   take care of, get done / boldogul, megold, rendbe tesz, elintéz
tolka                                   interpret, translate / tolmácsol, értelmez, magyaráz
tänka                                   think, imagine, intend / gondol, képzel, szándékozik
handla                                  buy, shop / vesz, vásárol, kereskedik, eljár
handla om                               deal with, be about / szól vmiről, tárgyal vmit
  [det handlar om dig]                    [rólad van szó]
tycka                                   think / gondol
tycka om                                like / kedvel, szeret
tillverka                               manufacture
trycka                                  print, press, weigh down / nyomtat, nyom, lenyom, rányom
känna                                   know, feel, sense / tud, ismer, érez, érzékel
vilja [ville]                           want / akar, szándékozik
skolka                                  cut class, play truant / lóg, bliccel, indokolatlanul távol marad
kunna [kunde]                           can, know / tud, képes vmire
tacka ja/nej                            yes/no, thank you (politely accept/decline) / köszönöm/köszönöm, nem
hämta                                   fetch, collect / elhoz, érte megy, begyűjt
paddla                                  paddle / evez
resa                                    travel, raise, put up, bring up / utazik, elutazik, (fel)emel, -állít, felkel
simma                                   swim / úszik
glömma [glömde]                         forget, neglect / elfelejt, elmulaszt
skramla                                 jingle, jangle, rattle / csörög, csörömpöl, zörög
duka                                    lay the table / megterít (asztalt)
snarka                                  snore / horkol, hortyog
vända                                   turn / elfordul, megfordul, vmit el/meg/kifordít
nå [når, nådde]                         reach / elér vmit/vmeddig
syssla [med ngn]                        busy oneself with sg / foglalkozik, foglalatoskodik, elfoglalja magát vmivel
betrakta                                consider, regard, look at, contemplate / (meg)szemlél, -tekint, -vizsgál, szemügyre vesz
böra                                    should, ought to / (segédige) kell, illik, -andó/-endő
steka                                   roast, fry / süt (roston/zsírban), pirít, párol
kasta                                   cast, throw, discard, throw away / (ki)dob, -hajít, -vet
svära                                   curse, swear / káromkodik, szitkozódik, esküdözik vmire
bestämma                                determine, prescribe, decide, settle / meg/elhatároz, elrendel, megállapít, kijelöl
skrika                                  scream, call out, cry, shriek, shout / kiált, kiabál, rikolt, ordít, üvölt
tjata                                   pester, nag / nyaggat, gyötör, korhol, zsörtölődik vkivel
fatta                                   catch, grasp, understand / felfog, megért, megfog
bruka                                   be in the habit of, cultivate / szokott ...-ni (segédige inf. alakú igével)
innebära                                involve, mean / tartalmaz, magában foglal, jelent, [vmivel] együtt jár
rycka                                   pull, snatch, tug / ránt, tép, szakít, meghúz
rycka in                                join up [for military service] / bevonul [seregbe]
rycka ut                                be demobilized [having completed mil.service] / leszerel [seregből]
uppstå                                  come up / keletkezik, létrejön, kerekedik, támad, indul
mönstra                                 scrutinize, sign on [mil] / vizsgál, mustrál, besoroz(zák) [seregbe]
ansöka                                  apply [for sg] / kérelmez, folyamodik, megpályáz, jelentkezik
sköta                                   look after, nurse, manage, treat, operate, tend, run, deal with / ápol, gondoz, törődik, gondoskodik, ellát, intéz, kezel, vezet
skryta                                  boast, brag / dicsekszik, felvág, kérkedik, nagyzol
välja [valde]                           choose, elect / választ, kiválaszt
ha nytta                                benefit, find useful / hasznára/előnyére válik
vänja [vande]                           accustom, get used to / hozzá/rá/megszokik vmit
be                                      ask, request, beg, pray / kér, kérlel, könyörög, felkér
rösta                                   vote / választ, szavaz
värna                                   protect / védelmez, oltalmaz, megvéd, óv
avskaffa                                do away with, get rid of, abolish / megszüntet, eltöröl, véget vet, hatályon kívül helyez
behålla                                 retain, keep, hold onto / megtart, fenntart, megőriz
fundera                                 think, ponder / elgondolkozik, megfontol, fontolgat, töpreng
beundra                                 admire / (meg)csodál, (meg)bámul, rajong
tråka (ut)                              tease, bug, bore / (halálra) untat, (ki)fáraszt
avsky                                   loathe, abhor, detest / utál, undorodik, irtózik, gyűlöl
försöka                                 try, attempt / megkísérel, meg/kipróbál, kísérletezik, igyekszik
framföra                                present, give, convey / átad, átnyújt, előad, elmond
tända                                   light, ignite / meggyújt, felgyújt, bekapcsol, felkapcsol (villanyt)
lämna                                   leave, give, hand / (ott)hagy, elhagy, hátrahagy, átenged, átad, nyújt, ad, hoz
släcka                                  extinguish, put out, slake, quench, turn/switch off / (el/ki)olt, kikapcsol, csillapít
träna                                   train, practise / gyakorol, treníroz, edz
öva                                     train, practise / gyakorol, betanul
klämma                                  pin, squeeze / szorít, szorongat, becsíp, nyom
förklara                                explain, declare, state / megmagyaráz, -világít, kijelent, kinyilvánít

** ANDRAS - OTHERS - EGYEBEK

mer                                     more / több
kort                                    short / rövid
främre                                  front / elülső
bakre                                   back / hátsó
lämplig                                 suitable, appropriate / megfelelő
tråkig                                  boring / unalmas
intressant                              interesting / érdekes
följande                                following / következő

tyvärr                                  unfortunately / sajnos
äntligen                                finally, at last / végül, végre
pigg                                    alert/spirited
hemifrån                                from home / otthonról
egen                                    own
avlång                                  oblong, rectangular, oval / hosszúkás, téglalap, elnyújtott
mulen                                   overcast / felhős
mörk                                    dark / sötét
fast                                    permanent, fixed, firm, solid
fortfarande                             still, continuous(ly)
ursprunglig                             original / eredeti
ursprungligen                           originally / eredetileg
vanlig                                  usual(ly), ordinary(-ily)
tystlåten                               taciturn / hallgatag
dryg                                    ample, more than, over, just over / bőséges
drygt                                   amply, over, just over / bőségesen
knapp                                   scarce, meagre / szűkös, szegényes, csekély, korlátozott
knappt                                  slightly less than, hardly / alighogy, nehezen, nem igen
ordentlig                               orderly, thorough / rendes, alapos
rejäl                                   strong, big, reliable, sure, serious, honest, substantial
rätt                                    right (straight), fairly, rather, quite
ren                                     clean, pure / tiszta (átv. is)
randig                                  striped, streaky / csíkos, sávos
rutig                                   checked, chequered / kockás
skär                                    light red, pink / halványpiros, rózsaszín
ung                                     young / fiatal
rik                                     wealthy, rich / vagyonos, gazdag
fattig                                  poor / szegény
vacker                                  beautiful / gyönyörű
duktig                                  able, capable / képes (vmire)
flitig                                  hard-working, diligent / szorgalmas
arbetsam                                hard-working / keményen dolgozó
hjälpsam                                helpful / segítőkész
lat                                     lazy / lusta
smal                                    thin, slim, narrow / vékony, keskeny
glad                                    pleased, happy / elégedett, boldog
trevlig                                 pleasant, likable (of person) / kellemes, kedves (személy)
berömd                                  famed, famous, celebrated / híres, nevezetes
känd                                    well-known / ismert, híres, neves
stark                                   strong, durable, solid, powerful
rolig                                   funny / szórakoztató, mulatságos, kellemes, tréfás
säker                                   safe, sure, certain, reliable / biztos, bizonyos, megbízható
farlig                                  risky, dangerous, hazardous / veszélyes, kockázatos
varlig                                  careful / óvatos, elővigyázatos
söt                                     sweet, cute / édes, aranyos
fort                                    quickly, fast / gyorsan, sebesen
rak                                     straight, honest / egyenes, öszinte
ledig                                   free, available / szabad, rendelkezésre álló
upptagen                                occupied, busy / foglalt, elfoglalt
hopplös                                 hopeless / reménytelen
arg                                     enraged, mad, angry / mérges, dühös, haragos
trasig                                  torn / rongyos, szakadt
elak                                    nasty, evil, wicked, naughty / gonosz, rossz, rosszindulatú, neveletlen
konstig                                 strange, curious, funny / különös, furcsa, szokatlan
ond                                     sore, wicked, annoyed / fájó (testrész), rossz, gonosz, haragos, dühös
härlig                                  lovely, glorious, delightful, wonderful / nagyszerű, remek, pompás, gyönyörű
blyg                                    timid, shy / szégyenlős, félénk, szemérmes
tung                                    heavy, major / nehéz, súlyos, nyomasztó, mély
smutsig                                 muddy, filthy, dirty / piszkos, szennyes, mocskos, sáros
sträng                                  strict, severe / szigorú, kemény, zord
hänsynsfull                             considerate / kíméletes, figyelmes, tapintatos
nog                                     enough, probably, of course / elég, eléggé, bizonyára [+nyomósító szóként]
noggrann                                careful / pontos, gondos, pedáns
rättvis                                 equitable, just, fair / igazságos, jogos, méltó
uppriktig                               frank, candid / őszinte, nyílt, becsületes
förstående                              understanding, sympathetic / megértő, együttérző
stolt                                   proud / büszke
renlig                                  clean, cleanly / tiszta, takaros, rendes
morgonpigg                              morning alert, morning person / koránkelő, hajnali pacsirta
beslutsam                               determined, resolute / határozott, elszánt
nyfiken                                 curious / kíváncsi
sparsam                                 thrifty, economical / takarékos, spórolós, beosztó
skyldig                                 in debt, owing, guilty / adós, tartozik, vétkes, bűnös, hibás
närvarande                              present / jelenlévő, jelenlegi, mostani
beroende                                dependent on / vmitől függő
närmare                                 closer, nearer / közelebb
utsatt                                  vulnerable / kitett (pl. veszélynek), kihelyezett, kitűzött, meghatározott
deprimerad                              depressed / lehangolt, levert
frisk                                   healthy, well / egészséges, üde, friss, élénk
sysslolös                               idle, inactive / tétlen, dologtalan
stekt                                   roast, fried / (meg)sütött, pirított, párolt, sült
sömnig                                  sleepy, drowsy / álmos

måndag                                  monday / hétfő
tisdag                                  tuesday / kedd
onsdag                                  wednesday / szerda
torsdag                                 thursday / csütörtök
fredag                                  friday / péntek
lördag                                  saturday / szombat
söndag                                  sunday / vasárnap

Va? / Vad?                              What? Mi?
Vem?                                    Who? Ki?
Hur?                                    How? Hogyan?
Var?                                    Where? Hol?
Vart?                                   Where to? Hová?
Varifrån?                               From where? Honnan?
Varför?                                 Why? Miért?
När?                                    When? Mikor?
Hurdan?                                 What (kind of)? Milyen? Miféle?

norr, norra                             the north, northern
syd/söder, södra                        the south, southern
öster, östra                            the east, eastern
väster, västra                          the west, western

varandra                                each other, one another
icke ...                                non-... / not-...
allmän                                  common, general
ihop                                    together / együtt
istället / i stället                    instead / vmi helyett
förutom                                 apart from, aside from / kívül, kivéve, azonkívül hogy ...

alltid                                  always
nästan alltid                           almost always
ofta                                    often
ibland                                  sometimes
sällan                                  seldom, rarely
aldrig                                  never
genast                                  immediately / azonnal

ganska                                  fairly, somewhat, rather, quite
visst                                   certainly, probably
egentligen                              actually, really / igazából, valójában
förstås                                 of course
javisst                                 of course, certainly
då                                      then
jo                                      well, yes, sure
jodå [~ jada...júra]                    sure, of course
tja                                     well (indicates doubt)
ju                                      of course, why
jamen, men                              why [expresses annoyance or surprise]
ojdå                                    nicsak
förresten                               by the way / egyébként
kul                                     cool, fun
särskilt                                particularly, especially
alltså                                  in other words, that is to say
sent                                    late
snart                                   soon, shortly / nemsoká, hamarosan
dessutom                                besides, moreover, in addition, furthermore
helst                                   rather, preferably
ändå                                    still, yet
heller                                  nor, neither, either, also
däremot                                 however, on the other hand
därför                                  therefore / emiatt, ennélfogva
därefter                                afterward, then, thereafter / (az/ez)után, miután
efteråt                                 afterwards / azután, utána
gärna                                   gladly, willingly / szívesen
redan                                   already / már
kvar                                    left (of sg, eg. space, time, etc.)
ikväll / i kväll                        tonight / ma este
därhemma                                back at home / odahaza
tvärtom / tvärt om                      on the contrary / fordítva, ellenkezőleg
sådan                                   such / ilyen, olyan
liksom                                  like, as, so to speak / mint, éppúgy mint, mintha
väl                                     well, very, too, surely / elég(gé), nagyon, bizonyára, ugye, ugyan
rädd                                    afraid, scared, frightened / félő, iject, aggódó
    rädd för ormar                          afraid of snakes
förkyld [~fösíld]                       having a cold / meg van fázva
bråttom                                 in a hurry, pressed / sietve, sürgősen
envis                                   obstinate, stubborn, persistent / nyakas, csökönyös, konok, szívós, kitartó
sakta                                   slowly, gently / lassan, enyhén
framme                                  in front, out / elöl, itt, ott
  [bilen vara framme]                     [az autó előállt]
iväg                                    away [from] / el [vhonnan]

udda                                    odd / páratlan
jämn                                    even, exact / páros, pontos(an annyi)
tyst                                    quiet, silent / csendes
minst                                   at least / legalább
samt                                    and (used @ end of list), as well as / és, még, valamint
nära                                    close to, almost / közel, majdnem
ner                                     down / le(nt)
höger                                   right / jobb
vänster                                 left / bal
mitt i                                  amid, midst / közte, közepette
förbi                                   past / túl rajta
utanför                                 outside of / kívüle
varken ~ eller ~                        neither ~ nor ~ / sem ~, sem ~
hemsk                                   horrible, ghastly, terrible / rettentő, roppant, ...
hemskt                                  awfully, terribly, frightfully / rettentően, roppantul, ...
äkta                                    authentic, real / valódi, echte
klar                                    clear / tiszta, derült, felhőtlen, rendezett
nöjd                                    satisfied / elégedett
värd                                    worth / [vmennyit] érő, [vmilyen] értékű
viss                                    certain / (egy) bizonyos
mest                                    most, the most / legtöbb, többnyire
flest                                   most / legtöbb
minst                                   least / legkevesebb
alldeles                                perfectly, altogether, quite, absolutely / teljesen, egészen, tökéletesen, rendkívül
hit                                     this way, here, hither / ide, erre
dit                                     that way, there, in that direction / oda, arra
annars                                  otherwise, else / egyébként, máskülönben
innan                                   until, before / mielőtt
överhuvudtaget                          on the whole, at all / általában, egészében, egyáltalán
nämligen                                namely, as, since, for / tudniillik, ugyanis, éspedig

eller hur?                              isn't it?, aren't you?, etc. / ugye?, nemde?
flermiljonfråga                         multi-million question

** Prepositioner

i                                       in / -ban
på                                      on / -on, rajta
under                                   under / alatt(a)
mitt emot                               opposite / szemközt, szemben vele
mellan                                  between / között
bakom                                   behind / mögött(e)
bredvid [brévi]                         beside, adjacent to / mellett(e), szomszédságában
runt omkring                            around / vmi. körül
mitt på                                 on/at the middle of... / vmi. közepén van/áll
över                                    over / felett(e)
framför                                 before / előtt(e)
ur                                      from, out of / -ból
trots                                   despite, in spite of / [vmi] ellenére
längst till vänster                     at the far left / a bal szélen
åt                                      at, to, towards, about / -nak/nek, felé

** Hjälpverb

brukar
bör
får
kan
måste
vill

** Fraser

Jag tror det.                           Azt hiszem (igen).
Hur står det till?                      ~ Hogy vagy?
Hur stavar du (till) det?               Hogyan betűzöd?
Vad heter det på svenska? Det heter...
Hur säger man på svenska? Man säger...

Vad gör ni?  (e: vajörni / vajornü?)
Vad är det för väder i Sverige nu?
Här skiner solen (e: her _Híner szúlen)

Javisst ja.                             Hát persze.
Inte särsklit.                          Semmi különös.

det snöar                               it's snowing
det regnar                              it's raining    
det blåser                              the wind is blowing
solen skiner                            the sun is shining
himlen är blå                           the sky is blue

 + plus
 - minus
 * gånger
 / delat med
 = är lika med

Nu är vi hos familjen Persson.
betalar räkningar                       fizeti a számlákat
efter en stund                          after a while
Dygnet runt                             Around the clock
Ibland är det förstås mulet!            Sometimes, of course, it is cloudy.
Hon är uppväxt i Brasilien.             She grew up in Brazil.

Så här ser den ut:                      This is how it looks like:

som en blixt från klar himmel           derült égből villámcsapás
Kul att se dig igen! [Kűlo szédeijen]   Nice to see you again!
kort sagt, ...                          in short, ...
i alla fall                             in any case / mindenesetre
Klär du i blått?                        Do you dress in blue?
Är det riktigt säkert?                  Is that really certain?
Vi har inte så bråttom.                 We are not in such a hurry.
Vi är inte framme!                      We are not there (yet)!
Har du några råd?                       Do you have any advice?
Spänn fast säkerhetsbältet, är du snäll!

borta bra men hemma bäst                there's no place like home
det handlar om dig                      this is about you / rólad van szó

Vad vill ni mig?                        What do you want from me?
Det håller jag med om.                  [On that] I agree [with you].

ju ..., desto ...                       the ..., the ...
  Ju närmare jag kom, desto mer nervös blev jag.
                                        The closer I got, the more nervous I became.
inte desto mindre                       none the less

Jag ska be att få...                    I'd like to ask for...
Jag skulle vilja ha...                  I'd like to have...
Kan jag få...?                          Can I have...?
Jag ska ha...                           I will have...
Skulle jag kunna få...?                 Could I get...?
Det var bra så.                         That's all.
Var det bra så?                         Is that all?
Något annat?                            Anything else?
Varsågod.                               Here you are. / You're welcome.

vart fjärde år                          every four years
Ta reda på                              Find out

Vi ses imorgon!                         See you tomorrow!
Vi hörs!                                See you!
Vi träffas ikväll!                      Meet you tonight!
Vi säger det!                           

Beklagar, men ...                       Sorry, but ...
Får jag tala med ...                    May I talk to ...
Det ät upptaget.                        It is busy.
Ett ögonblick!                          Just a moment!
Jag söker ...                           I'm looking for
Vem kan jag hälsa från?                 
Kan du framföra det?                    Can you convey that?
Han sitter tyvärr i sammanträde.        Unfortunately he is in a meeting.
Hon är tyvärr på tjänsteresa.           She is unfortunately on a business trip.
Det kan inte hjälpas.

ge sig iväg                             set off
En dag var till ända.                   A day was over.

** Ordspråk

Den som gräver en grop åt andra, faller själv däri.
                                        He who digs a pit for others will fall therein.
Som man bäddar, får man ligga!          As you make your bed, so you must lie upon it!
Man kan aldrig lära gamla hundar att sitta.
                                        You cannot teach an old dog new tricks.
Äta bör man, annars dör man.            One must eat, or one dies.
Tala är silver, tiga är guld.           Speech is silver, silence is golden.

** Några uttryck med djur

Stark som en björn                      Erős mint egy medve
Listig som en räv                       Ravasz mint egy róka
From som ett lamm                       Jámbor (~ártatlan) mint egy bárány
Flitig som en myra                      Szorgalmas mint egy hangya
Modig som ett lejon                     Bátor mint egy oroszlán
Dum som en åsna                         Buta mint egy szamár
Vig som en apa                          Fürge mint egy majom

** Några tidsuttryck

igår                                    yesterday / tegnap
i förrgår                               the day before yesterday / tegnapelőtt
förra veckan                            last week / múlt hét
förra månaden                           last month / múlt hónap
förra året                              last year / tavaly
för en timme sedan                      an hour ago / egy órája
för en minut sedan                      a minute ago / egy perce
för tre dagar sedan                     three days ago / három napja
för en vecka sedan                      a week ago / egy hete
för en månad sedan                      a month ago / egy hónapja
för ett år sedan                        a year ago / egy éve
imorse                                  this morning / (ma) reggel
i måndags [i måndas]                    last monday / múlt hétfőn
i tisdags                               last tuesday / múlt kedden
i onsdags                               last wednesday / múlt szerdán
i vintras                               last winter / a(z elmúlt) télen
i våras                                 last spring / a(z elmúlt) tavasszal
i somras                                last summer / a(z elmúlt) nyáron
i höstas                                last fall/autumn / a(z elmúlt) ősszel

imorgon bitti                           tomorrow (early) morning
imorgon kväll                           tomorrow evening/night
i övermorgon                            on the day after tomorrow
på onsdag (morgon, kväll)               on wednesday (morning, evening/night)
nästa onsdag                            next wednesday
nästa vecka                             next week

** Rövidítések

osv. [och så vidare]                    etc. / stb.
jfr. [jämför]                           cf. / vö.
dvs. [det vill säga]                    i.e. / azaz, úgymint
OBS!                                    Attention!
ToR [Tur och retur]                     oda-vissza/retúr

** Káromkodások, indulatszavak

fan, fy fan, fan också - francba/fenébe (is)
skit - szar
jävla - fokozás (~ bloody, damned, goddamned)
jävla bra
jävla skit (erős)
helvete - pokolba (enyhe)
satan
kuk, fitta
as - ass, asshole
kronsoppa ~ "királyi" (méretes) szopás
sjutton, tusen: indulatszavak, kb. ~WTF
din jävla skitstövel ~ you fucking asshole/motherfucker


* Grammatik

** ALFABETET (p.4)

abcdefghijklmnopqrstuvwxyzåäö

Vokaler: aeiouyåäö
Främre: eiyäö
Bakre: aouå

Konsonanter: bcdfghjklmnpqrstvxz
W bara i namn

** PRONOMEN

|         | Nominativ    | Genitiv               | Accusativ/Dativ     | Reflexiv |
|---------+--------------+-----------------------+---------------------+----------|
| E/1     | jag     [én] | min/mitt/mina [enyém] | mig   [engem/nekem] | mig      |
| E/2     | du      [te] | din/ditt/dina  [tiéd] | dig   [téged/neked] | dig      |
| E/3 hn. | han      [ő] | hans            [övé] | honom     [őt/neki] | sig      |
| E/3 nn. | hon      [ő] | hennes          [övé] | henne     [őt/neki] | sig      |
| E/3 en  | den     [az] | dess            [azé] | den     [azt/annak] | sig      |
| E/3 ett | det     [az] | dess            [azé] | det     [azt/annak] | sig      |
|---------+--------------+-----------------------+---------------------+----------|
| T/1     | vi      [mi] | vår/vårt/våra [miénk] | oss [minket/nekünk] | oss      |
| T/2     | ni      [ti] | er/ert/era   [tiétek] | er [titeket/nektek] | er       |
| T/3     | de [ők/azok] | deras    [övék/azoké] | dem    [őket/nekik] | sig      |
|         |              |                       |    [azokat/azoknak] |          |

** VERB I PRESENS = -r/-er (p.1)

talar
arbetar  -r efter vokal
bor

heter    -er efter konsonant
kommer

** ORDFÖLJD (p.2)

| 1         | 2      | 3       | 4             |
| FUNDAMENT | VERB   | SUBJEKT | ANNAT         |
|-----------+--------+---------+---------------|
| Jag       | bor    | -       | i Stockholm.  |
| Jag       | talar  | -       | svenska.      |
| Hon       | kommer | -       | från Finland. |
| Vad       | heter  | du?     |               |
| Vad       | talar  | du      | för språk?    |
| Var       | bor    | han?    |               |

Subjekt = fundament -> plats 3 tom! Verb på 2:a plats.

** ORDFÖLJD I FRÅGOR (p.3)

ja-nej-frågor, inget frågeord

| 1 | 2      | 3   | 4         |
| F | V      | S   |           |
| - | Kommer | du  | från USA? |
| - | Läser  | han | svenska?  |

Ja-nej-fråga: 1:a plats tom! Verb på 2:a plats.

** OBESTÄMD ARTIKEL + SUBSTANTIV (p.7)

en/ett substantiv
  en   stol
  ett  bord
  en   lärare
  ett  barn
  en   pojke
  ett  universitet

YRKEN utan artikel
  jag är lärare
  du är polis
  han är fotograf
  hon är astronom

** ORDFÖLJD (p.10)

| 1            | 2      | 3   | 4                 |                       |
| F            | V      | S   | A                 |                       |
|--------------+--------+-----+-------------------+-----------------------|
| Patrik       | vaknar | -   | klockan åtta.     | (fundament = subjekt) |
| Klockan åtta | vaknar | han | -.                | (fundament = tid)     |
| Han          | äter   | -   | frukost halv nio. | (fundament = subjekt) |
| Frukost      | äter   | han | halv nio.         | (fundament = objekt)  |
| Klockan nio  | går    | han | hemifrån.         | (fundament = tid)     |
| Hem          | kommer | han | klockan fem.      | (fundament = plats)   | 

Verb på 2:a plats!  

** SATSFOGNING MED OCH (p.11)

| 1     | 2       | 3   |     | 1     | 2      | 3    |                  |
| F     | V       | S   | och | F     | V      | S    |                  |
|-------+---------+-----+-----+-------+--------+------+------------------|
| Hon   | duschar | -   | och | -     | ringer | -    | till en väninna. |
| Hon   | duschar | -   | och | sedan | ringer | hon  | till en väninna. |
| Sedan | duschar | hon | och | -     | ringer | -    | till en väninna. |
| Kl 9  | börjar  | hon | och | kl 5  | slutar | hon. |                  |

Efter *och*: upprepa inte subjektet!
Efter *och + fundament*: upprepa subjektet!

fundament = inte subjekt

** SUBSTANTIV (p.13)

| OBESTÄMD        | BESTÄMD FORM  | Bestämd artikel     |             |
|-----------------+---------------+---------------------+-------------|
| en kvällskurs   | kvällskursen  | -en efter konsonant |             |
| en lektion      | lektionen     |                     |             |
|                 |               |                     | för en-ord  |
| en klocka       | klockan       | -n efter vokal      |             |
| en pojke        | pojken        |                     |             |
|-----------------+---------------+---------------------+-------------|
| ett jobb        | jobbet        | -et efter konsonant |             |
| ett universitet | universitetet |                     |             |
|                 |               |                     | för ett-ord |
| ett äpple       | äpplet        | -t efter vokal      |             |
| ett piano       | pianot        |                     |             |

** ARTIKEL ELLER INTE? (p.15)

| Olle är författare.                | yrke                                      | ingen artikel      |
| Nu arbetar han på en roman.        | presentation, första gången               | obestämd artikel   |
| Han har självdisciplin!            | icke räkningsbart                         | ingen artikel      |
| Klockan åtta äter han frukost.     | uttryck med äter                          | ofta ingen artikel |
| Han läser tidningen.               | han har bara en morgontidning             | bestämd artikel    |
| Klockan nio sitter han vid datorn. | han har bara en dator                     | bestämd artikel    |
| Han röker en cigarrett.            | det finns många                           | obestämd artkel    |
| Han tittar ut genom fönstret.      | det finns ett fönster framför skrivbordet | bestämd artikel    |
| Han skriver ungefär ett kapitel.   | det finns flera kapitel i boken           | obestämd artikel   |
| Han lyssnar på musik.              | icke räkningsbart                         | ingen artikel      |
| Han svarar på brev.                | allmän betydelse                          | ingen artikel      |

** SITTER, LIGGER, STÅR, HÅLLER PÅ (p.19)

han *sitter och* pluggar
hon *ligger och* läser
de *står och* pratar
hon *håller på och* stickar

De gör något *just nu*.

** HUVUDSATS MED SATSADVERB (p.21)

| 1      | 2       | 3   | 4        | 5        |
| F      | V       | S   | S-ADVERB | RESTEN   |
| Jag    | går     | -   | sällan   | på bio.  |
| Hon    | tittar  | -   | alltid   | på teve. |
| Ibland | fiskar  | han | -        | .        |
| De     | skriver | -   | aldrig   | brev.    |

** GENITIV: SUBST + S (p.29)

Lottas arbete
Professor Bergmans bil
Mammas och pappas säng
Texas befolkning är 18 miljoner

Ord som slutar på -s, -x eller -z får inget extra -s.
(Svenskan använder oftast ingen apostrof.)
Texas befolkning
Schweiz huvudstad
Max syster

** DET ÄR EN/ETT/PLURAL (p.34)

Vid presentering av någon/något använder man frasen
*Det är...*
   det är en sjö
   det är ett landskap
   det är herr Öhman
   det är herr och fru Sjöberg

** PLURAL (p.35)

1. -or  en krona               två kronor
2. -ar  en avdelning           två avdelningar
        en köttbulle           två köttbullar
3. -er  en apelsin             två apelsiner
   -r   en sko                 två skor
4. -n   ett äpple (vokal)      två äpplen
5. -    ett päron (konsonant)  två päron
        en lärare              två lärare

Det finns inte regler för pluralformer för alla substantiv!

** DET FINNS + OBESTÄMT SUBSTANTIV (p.36)
                                                 några en-ord på
          en    sportavdelning på varuhuset.     -el  cykel  cyklar
Det finns ett   varuhus        i staden.         -en  fröken fröknar
          många avdelningar    på ett varuhus.   -er  åker   åkrar

** UTTRYCK FÖR FREKVENS (p.38)

två gånger i minuten
           i timmen
           i veckan
           i månaden

två gånger om dagen
           om året

"naturliga" tider = jorden går runt ett varv om dagen,
                    jorden går runt solen ett varv om året

** ORDFÖLJD (p.42)

| fundam. | verb   | subj. | adverb | partikel | objekt |
|---------+--------+-------+--------+----------+--------|
| Han     | tycker |       | inte   | om       | mjölk  |
| Hon     | tycker |       |        | om       | öl     |
| Vad     | tycker | du    | inte   | om       | ?      |
| Vad     | tycker | du    |        | om       | ?      |

Alltså: partikel *före* objekt och *efter* satsadverb

** BESTÄMD FORM PLURALIS (p.43)
                                         Plural
skolor   skolorna
bilar    bilarna   en-ord                -na
filmer   filmerna

äpplEn   äpplena   ett-ord på vokal      -a
huS      husen     ett-ord på konsonant  -en

** PRONOMEN SOM SUBJEKT OCH OBJEKT (p.47)

Hon behöver en bok.         Den kostar 50 kronor.
                            Den köper hon. (Hon köper den).

Hon behöver ett halsband.   Det kostar 50 kronor.
                            Det köper hon. (Hon köper det).

Hon behöver örhängen.       De kostar 50 kronor.
                            Dem köper hon. (Hon köper dem).

de              I brev, kvällstidningar och barnböcker skriver man ofta dom.
     [dom]      I vissa dialekter säger man [di] och [dem].
dem             I radio och teve säger man nu ofta: [de] respektive [dem].

** OBJEKTSPRONOMEN (p.49)

| subjektspronomen | objektspronomen   |
|------------------+-------------------|
| jag [ja] *       | mig / mej** [mej] |
| du               | dig / dej** [dej] |
| han              | honom             |
| hon              | henne             |
| vi               | oss               |
| ni               | er                |
| de [dom]         | dem [dom]         | 

 * I obetonad stavelse.
 ** Nuförtiden skriver man ofta "mej" och "dej" i vardaglig stil.
  
** ADJEKTIV (p.52)

ADJEKTIV / attributivt

|     | adjektiv | obest subst |                  |
|-----+----------+-------------+------------------|
| en  | svensk   | bil         | ADJ (i ordlista) |
| ett | svenskt  | hus         | ADJ + t          |
| två | svenska  | bilar       | ADJ + a          |
| två | svenska  | hus         |                  |

ADJEKTIV / predikativt

|              | kopula | adjektiv               |         |
|--------------+--------+------------------------+---------|
| en tidning   | är     | svensk och en är dansk | ADJ     |
| ett hus      | är     | gult och ett är grönt  | ADJ + t |
| fyra blommor | är     | röda och tre är vita   | ADJ + a |

Adjektiv på -d:    Konsonant +t:       -vokal:
en röd bil         en svart bil        en blå bil
ett rött hus       ett svart hus       ett blått hus
två röda bilar     två svarta bilar    två blå(a) bilar

** FÄRGER (p.53)

| regel- | -d        |               |
| bundna | -kons + t | oregelbundna* |
|        | vokal     |               |
|--------+-----------+---------------|
| gul    | röd       | orange        |
| grön   | svart     | rosa          |
| brun   | glå       | lila          |
| vit    | grå       |               |
| skär   | violett   |               |

 * samma form i en-, ett-ord och plural

vokal + l,r,n + a           vokalen försvinner
n + t                       n försvinner
två m bara mellan vokaler

Exempel: enkel + a     enkla
         liten + t     litet
         gammal        gamla

** DEMONSTRATIVA PRONOMEN + BESTÄMD ÄNDELSE (p.57)

den här väskan       den där väskan
det här huset        det där huset
de här  väskorna     de där  väskorna
de där  husen        de där  husen

** KORTSVAR, "EKOSVAR" (p.59)

I svaret _upprepar_ man frågans verb, om det är *är* eller *har*:
  Har du tid? -Ja, det har jag.
  Är du trött? -Ja, det är jag.

annars _ersätter_ man det med *gör*:
  Sover du? -Nej, det gör jag inte.
  Bor han i Malmö? -Ja, det gör han.

** JA, JO, NEJ, DET GÖR DET (INTE) (p.60)

Ligger Stockholm i Sverige?          *Ja*, det gör det.
Ligger *inte* Stockholm i Sverige?   *Jo*, det gör det.
Ligger Stockholm i Danmark?          *Nej*, det gör det inte.

Om man frågar med inte, svarar man jakande med *jo*.

** FREKVENS / HUR OFTA? (p.61)

tre paket *om dagen*
en gång *om året*

en flaska vin *i veckan*
två gånger *i månaden*
en gång *i timmen*
åtta timmar *om dygnet*
fyra gånger *i minuten*
en gång *i sekunden*

** DEN / DET / HAN / HON / DE

Vad är det (här)? Det är en elefant! Den bor i Afrika.   (syftar på elefanten)
Vad är det (där)? Det är ett lejon.  Är det farligt?     (syftar på lejonet)
Vad är det (här)? Det är sebror.     De är randiga.      (syftar på sebrorna)
Är det en hane?   Ja, det är det.    Han är mycket stor. (syftar på en hanelefant)
Är det ett lejon? Ja, det är det.    Hon heter Elsa.     (syftar på en lejonhona)

** IMPERATIV (p.64-65)

Imperativ = stammen

tala! jfr presens talar = imperativ + r
läs!  jfr presens läser = imperativ + er (efter konsonant)
gå!   jfr presens går   = imperativ + r

var!  jfr presens är (oregelbundet)

Från presens till imperativ:
Ta bort  -r efter vokal (som inte är e) och
         -er efter konsonant!

Exempel: stannar -> stanna!  äter -> ät!  står -> stå!

Några verb slutar på -r i imperativ:
    kör
    gör
    hör etc.
De får inte +er i presens.
Deras presensform = imperativform!

** POSSESSIVA PRONOMEN (p.67)

en     tavla     ett    hus     många  frågor
min    tavla     mitt   hus     mina   frågor
din    tavla     ditt   hus     dina   frågor
hans   tavla     hans   hus     hans   frågor
hennes tavla     hennes hus     hennes frågor
vår    tavla     vårt   hus     våra   frågor
er     tavla     ert    hus     era    frågor
deras  tavla     deras  hus     deras  frågor

1 och 2 person singularis och pluralis böjs som adjektiv = -t, -a.
3 person sing och plur böjs inte.

-Vems tavla är det där?     -Det är min.  (Man upprepar inte substantivet.)
-Vems hus är det där?       -Det är mitt.
-Vems strumpor är det där?  -Det är mina.

** SLÄKTORD (p.69)

Släktord är mycket oregelbundna:

en bror (broder)  två bröder
en syster         två systrar
en mor (moder)    två mödrar
en far (fader)    två fäder
en farbror        två farbröder
en moster         två mostrar
en son            två söner
en dotter         två döttrar
en mormor         två mormödrar
en farmor         två farmödrar
en morfar         två morfäder
en farfar         två farfäder

** RELATIVT PRONOMEN SOM (p.70)

syftar tillbaka på personer och saker.
en- eller ett-ord, sing. eller plural
  ... en bror, som heter...
  ... ett barn, som går i ...
  ... en bok, som står i ...
  ... ett land, som ligger i ...
  ... två vänner, som ...
  ... två böcker, som ...

** PRETERITUM (p.72)

förfluten tid / dåtid / imperfekt -de
                                     presens    preteritum
Stam på -a                           kosta -r   kosta -de
Stam på konsonant  Tonande           lev   -er  lev   -de
Stam på konsonant  Tonlös: k p s t   köp   -er  köp   -te  (man kan inte säga d)
Stam på vokal      men inte -a       bo    -r   bo    -dde (man måste förlänga d)

Några verb är oregelbundna           ä     -r   var        (de saknar ofta ändelse)

** MAN / EN / ENS (p.79)

I Sverige får *man* rösta,  (subjekt)
när *man* blir 18 år.       (subjekt)
*Man* blir glad,            (subjekt)
när *ens* barn kommer       (genitiv)
och besöker *en*.           (objekt)

*Man* använder man bara för subjektet;
annars använder man *ens* och *en*.

** RELATIVSATSER (p.79)

           *subjekt*                               *objekt*
De som var på festen var trevliga.     Jag känner dem som var på festen.
Alla som var på festen var trevliga.   Du känner alla som var där.
Någon som du känner var där.           Fråga någon som var där.
Ingen som du känner var där.           Jag känner ingen som tänker gå på festen.

** HJÄLPVERB + INFINITIV (p.80)

|     | hjälp | (adv)  | inf    |         |
|-----+-------+--------+--------+---------|
| Jag | kan   | (inte) | spela  | piano.  |
| Hon | vill  | (inte) | betala | skatt.  |
| De  | måste |        | tvätta | kläder. |

** MODALA HJÄLPVERB (p.83)

| Fundament | Verb 1    | Subjekt | Adverb       | Huvudverb |
|           | hjälpverb |         |              | infinitiv |
|-----------+-----------+---------+--------------+-----------|
| Du        | behöver   | -       | inte         | betala.   |
| Jag       | måste     | -       | nog          | gå.       |
| Hon       | får       | -       | gärna        | sjunga.   |
| Vi        | vill      | -       | naturligtvis | komma.    |
| Varför    | kan       | du      | inte         | ringa?    |
| När       | måste     | vi      | -            | resa?     |
| Imorgon   | får       | du      | -            | sova.     |
| -         | Måste     | jag     | verkligen    | åka?      |
| -         | Får       | han     | inte         | komma?    |

** INFINITIV MED ELLER UTAN "ATT" (p.88)

Jag måste skriva till Filip.  Jag tycker /om/ *att* skriva.
Jag vill inte gå på festen.   Hon glömmer ofta /bort/ *att* ringa hem.
De får inte komma hit.        Jag lovar *att* komma.
Hon kan tala fem språk.       Hon älskar *att* tala franska.

Efter hjälpverb har man inte *att* före infinitiv.
Efter några verb (speciellt verb med /partikel/) har man *att* före infinitiv.
Man måste lära sig regeln för varje verb.

** VILKEN/VILKET (p.89)

Vilken är din favoritfärg?   (en färg)
Vilket är ditt favoritdjur?  (ett djur)
Vilka är dina favoritfärger? (många färger)

** VARANDRA (p.90)

De älskar varandra. (Han älskar henne och hon älskar honom.)
Vi hjälper varandra. (Jag hjälper dem och de hjälper mig.)
Vi lånar varandras kläder. (Jag lånar hans kläder och han lånar mina.)

Vi träffas på måndag! (Vi träffar varandra på måndag.)
Vi hörs! (Vi hör av varandra.)

** PRETERITUMFORMEN (p.92)

Preteritumformen -de för verb som slutar på -a i imperativ uttalas
inte alltid i talspråk.

Exempel:
Han titta' på teve igår.
Hon tala' med Pelle i förrgår.
Han plantera' på marken.

I skrift markerar man det ibland med ett '-tecken.

** STARKA OCH OREGELBUNDNA VERB (p.93)

| presens      | preteritum   |          |
|--------------+--------------+----------|
| är           | var          | oregelb. |
| går          | gick         | oregelb. |
| ser ut       | såg ut       | oregelb. |
| stiger upp   | steg upp     | starkt   |
| sätter på    | satte på     | oregelb. |
| gör          | gjorde       | oregelb. |
| sitter       | satt         | starkt   |
| äter         | åt           | starkt   |
| ger sig iväg | gav sig iväg | oregelb. |
| måste        | måste        | oregelb. |
| kommer       | kom          | starkt   |
| kan          | kunde        | oregelb. |
| ligger       | låg          | oregelb. |

Många verb är oregelbundna bara i /en/ form.

Man ser inte alltid på preteritumformen om ett verb är starkt eller
oregelbundet.


* Övningar i Lärobok

** p.27: En intervju

1. Hon heter Britta Holmberg.
2. Hon bor och arbetar i Nyköping.
3. Hon arbetar på en skola i Nyköping.
4. Hon är lärare i svenska och engelska.
5. Hon börjar kvart över åtta på morgonen.
6. Hon stiger upp klockan halv sju.
7. Hon dricker en kopp tee och äter en smörgås eller två.
8. Klockan sju tar hon alla böcker och går.
9. Hon åker bus till skolan.
10. Bussen går tio över sju.
11. Hon kommer halv åtta fram till skolan.
12. På bussen sitter hon och läser tidningen.
13. Klockan halv ett äter hon lunch.
14. Hon äter bara en smörgås ellen en joghurt eller ett äpple.
15. Hon slutar klockan tre eller fyra.
16. Klockan sex lagar hon middag.
17. På kvällen sitter hon och läser eller stickar eller
    pratar i telefonen men ibland går hon ut och dansar
    eller jumpar ??? träffa vänner; hon går och läser
    italienska också.

** p.31: Lyssna på bandet och lös fler problem!
1. 5 + 8 = 13 (tretton)
2. 16 - 11 = 5 (fem)
3. 18 / 3 = 6 (sex)
4. 5 * 3 = 15 (femton)
5. 13 - 10 = 3 (tre)
6. 17 + 4 = 21 (tjugoett)
7. 21 / 3 = 7 (sju)
8. 7 * 2 = 14 (fjorton)
9. 19 + 7 = 26 (tjugosex)
10. 24 / 6 = 4 (fyra)
11. 30 - 5 = 25 (tjugofem)
12. 45 + 5 = 50 (femtio)
13. 60 - 20 = 40 (fyrtio)
14. 80 + 10 = 90 (nittio)
15. 50 / 5 = 10 (tio)

** p.32: Fyll i rätt procenttal!
   Går och badar 42%
   Läser böcker 40%
   Går på bibliotek 30%
   Syr, stickar eller väver 28%
   Går på restaurang 25%
   Går ut och dansar 23%
   Tittar på idrott 22%
   Fiskar 20%
   Går på bio 15%
   Går i kyrkan 11%
   Går på kurs 11%
   Skriver brev och dagbok 12%
   Spelar ett instrument 7%
   Går på konsert 6%
   Fotograferar eller filmar 6%
   Sjunger i kör 4%
   Samlar frimärken, mynt etc. 4%
   Går på teater 4%
   Spelar bingo 4%

** p.34: En dialog

- Hej! Vad heter du?
- Kerstin Schön.
- Hur stavar du din efternamn?
- S-C-H-Ö-N.
- Du kommer inte från Sverige, va?
- Nej, jag kommer från Finland, men min pappa är tysk.
- Var bor du nu?
- På Hantverkargatan. På Kungsholmen alltså.
- Varför är du då?
- Jag är här på semester.
- Och vad gör du då?
- Jag badar, solar och brädseglar ibland.
- Vad talar du för jobbet?
- Jag jobbar på ett apothek.
- Är det intressant?
- Nää! Det är jättetråkigt!
- Hur gammal är du?
- 21. Snart 22.
- Vad gör du på lördag?
- På lördag? Inget speciellt.
- Jätte bra! Då går vi ut tillsammans och dansar!
- Ja, varför inte?

** p.40: Lyssna på bandet
1. Johan cyklar till jobbet.
2. Elisabeth åker buss till kvällskursen.
3. Margareta åker bil till kontoret.
4. Åke åker tåg till jobbet.
5. Familjen Svensson tar bilen till arbetet.
6. Läraren går till skolan.
7. Direktör Berg åker taxi till fabriken.
8. Eleven åker tunnelbana till universitätet.

** p.43: Skriv bestämd form (sing. eller plur.) till:

| telefon          | telefonen   |
| klocka           | klockan     |
| hus (sing.)      | huset       |
| hundar           | hundarna    |
| brev (sing.)     | brevet      |
| piano            | pianot      |
| päron (plur.)    | päronen     |
| lektioner        | lektionerna |
| frågor           | frågorna    |
| maskiner         | maskinerna  |
| våning           | våningen    |
| pass (plur.)     | passen      |
| bussar           | bussarna    |
| svar (sing.)     | svaret      |
| yrken            | yrkena      |
| diskotek (plur.) | diskoteken  |
| bil              | bilen       |
| poliser          | poliserna   |
| lampa            | lampan      |
| frukost          | frukosten   |
| paket (plur.)    | paketen     |
| kunder           | kunderna    |
| böcker           | böckerna    |
| kamrater         | kamraterna  |
| skåp (plur.)     | skåpen      |
| problem (sing.)  | problemet   |
| problem (plur.)  | problemen   |

** p.44: Svara på frågorna!
1. Det finns inte så många bönder i Sverige.
2. Ett jordbruk är 34 hektar stort i genomsnitt.
3. Bara drygt två procent av alla svenskar arbetar inom jordbruket.
4. Bönderna odlar vete, råg, raps eller potatis.
5. Bönderna har kor, får, svin, höns, kycklingar.
6. Från kor får vi mjölk och kött, från svin fläsk, från fåren ull ock kött, från hönsen ägg.
7. En ko ger 8400/365= cirka 23 (tjugotre) liter mjölk per dag.
8. Vi importerar tomater, gurka och apelsiner. Vi importerar inte trä och järn.

** p.44: Varifrån är de?
Teven är från Japan.
Stövlar är från Finland.
Lampan är från Tyskland.
Tulpaner är från Holland.
Klockan är från Schweiz.
Datorn är från Hong Kong.
Bordet är från Tjeckien.
Osten är från Danmark.
Glaset är från Italien.

** p.46: Titta på bilderna! Var står soffan, sängen etc.?
Fåtöljen står framför bokhyllan.
Böckerna står i bokhyllan.
Mannen sitter i fåtöljen.
Vasen står under lampan.
Lampan står mellan teven och blomman.
Bordet står mitt på golvet.

** p.48: Sätt in rätt pronomen: den, det, de eller dem.
De
Den
Det
Den
De
Det
Dem
De
Det
dem
den
det

** p.50: Vilka pronomen passar? Fyll i luckorna!
- Jag älskar dig. Älskar du mig?
- Hon älskar honom men han älskar inte henne.
- Vi tänker på dem men de tänker aldrig på oss.
- Ni är välkomna till oss idag, så kommer vi hem till er imorgon.
- Träffar du mig i kväll?
- Ja.
- Hälsa dig från dem!
- Kan du Lisas telefonnummer? Jag måste ringa till henne ikväll.
- Känner du Ingrid och Hasse? Vi spelar bridge hemma hos dem varje torsdag.

** p.50: Lyssna på bandet! Skriv ner deras dialog!
- Saknar du mig?
- Ja, jag saknar dig mycke!
- Längtar du efter mig?
- Ja, jag längtar efter dig varje sekund!
- Älskar du mig?
- Jag älskar dig så mycket, så mycket!
- Ringer du till mig imorgon?
- Ja, jag ringer till dig efter middag.

** p.52: Nationalitetsadjektiv
1. Det är en japansk bandspelare.
2. Mercedes-Benz är en tysk bil.
3. Egri Bikavér är ett ungerskt vin.
4. Volvo och Saab är svenska bilar.
5. Mozart är en österrikisk kompositör.
6. Tsing Tao är ett kinesisk öl.
7. "Sauna" är ett finskt ord.
8. Zubrowka är en polsk vodka.
9. Federico Fellini är en italiensk regissör.
10. Dallas är en amerikansk stad.
11. Dostojevskij är en rysk författare.
12. Pablo Picasso är en spansk målare.
13. SKF är ett svenskt företag.

** p.53: Adjektiv och substantiv
en svart väska
en billig kamera
två röda hus
nya skor
gula gardiner
en hård säng
ett litet rum
en dum fråga
många intelligenta vänner
många svåra problem
ett vit papper
två intressanta artiklar
en gammal radio
ett roligt barnprogram
ett gammalt band
många vackra blommor
två små diamanter

** p.56: Lyssna på bandet och skriv!

Nicklas är ogift och bor ensam i en liten våning mitt i Stockholm.
Han är inte ensam om det: i Stockholm bor 62% av invånare ensamma.
Han är ganska kort: 1 och 72 och det retar honom. Därför har han ofta
skor med tjocka sulor. Han har brunt hår. Just nu är det ganska
långt. Han tjänar ganska bra men han är inte rik. Hyran är dyr och
maten: han äter gärna på dyra och fina restauranger. Och hans kläder
är inte billiga heller. Han tycker om snygga, moderna kläder. Han är
ganska nöjd med livet.

** p.59: Svara med kortsvar enligt modellen:

1. Ja, det gör de.
2. Nej, det har hon inte.
3. Ja, det är de.
4. Nej, det gör hon inte.
5. Nej, det gör jag inte.
6. Ja, det har han.
7. Ja, det gör jag.
8. Nej, det gör hon inte.
9. Ja, det gör de.
10. Nej, det gör jag inte.
11. Nej, det har jag inte.
12. Nej, det gör jag inte.
13. Nej, det gör han inte.
14. Nej, det gör jag inte.
15. Ja, det gör hon.
16. Nej, det är de inte.
17. Ja, det har vi.
18. Nej, det gör jag inte.
19. Ja, det gör jag.
20. Ja, det har hon.

** p.60: Ja, jo eller nej

1. Nej, det gör det inte.
2. Jo, det gör han.
3. Ja, det gör de.
4. Jo, det gör han.
5. Jo, det gör de.
6. Nej, det gör de inte.
7. Nej, det har de inte.
8. Nej, det har de inte.
9. Nej, det är hon inte.
10. Ja, det gör det.

** p.61: Hos doktorn. Lyssna på bandet
1.
- Jo, doktorn, jag har(s?) ont i magen.
- Varsågod och sitt. Vad gör du ont? Här?
- Ajjjj! Ja, just det. Det svider hela tiden.
- Jaha. Röker du mycket?
2.
- Nej, det gör jag inte.
- Hur mycket?
- Tja 2 paket om dagen, kanske.
3.
- Äter du bra?
- Ja, ...
  Kaffe till frukost, lunch äter jag ute och middag också ibland.
4.
- Har du stress åt arbete?
- Ja, det har jag. Jag är försäljare.
  Jag reser omkring och säljer flipperspel.
- Hoppar du inte över lunchen ibland då?
- Jo, det händer. Då tar jag en fika istället.
5.
- Dricker du mycket kaffe?
- Ja, gör jag det. ... 5-6 kopper om dagen blir ...
- Och ibland går du ute och äter middag med kunderna också.
  Dricker du inte ... då?
6.
- Nej, inte så mycket.
  Men en par flaska vin i veckan blir ...
7.
- Motionerar du?
- Nej, det gör jag inte. Jo, förresten, jag spelar golf en eller
  två gånger i månaden.
8.
- Det här ser inte så bra ut.
  Du har för högt bludtryck och du väger för mycket.
  Du får snart magsår. Slutar med kaffe. Kaffe är inte allts bra för dig.
- Inte?
- Nej, kaffe, sprit, salt och fettmat är förbjudet hedan(?) efter.
- Herre gud, vad ska jag då äta?
- Mager fisk. Bröd. Grönsaker. Drick vatten. Sov ordentligt och slarva inte
  med lunchen. Du är inte tjugo längre.
- Nej, det är jag inte. Men jag är ju inte åttio heller.
- Nej, det är sant. Men det här ser inte bra ut.
  Komm tillbaka om en månad. Och du!
- Ja?
- Skär ner på cigarrettena också, är du snäll.

** p.63: Svenska djur

- Vad är det här?
- Det är en varg. Den lever huvudsakligen i norra Sverige,
  men det finns vargar i södra Sverige också.

- Vad är det här för djur?
- Det är en järv. Den finns också i norra Sverige,
  men bara ca 100 stycken.

- Vad är det här för någonting?
- Det är en älg. Den är en mamma, som har två små kalvar.
  De är mycket söta.

- Vad är det här då?
- Det är ett lodjur.
- Det ser ut som en stor katt.
- Ja, det är ett kattdjur också.

** p.64: Vad är imperativformen?

talar - tala!
läser - läs!
dricker - drick!
röker - rök!
ringer - ring!
ser - se!
flyttar - flytta!
ställer - ställ!
diskar - diska!
lagar - laga!
skriver - skriva!
ger - ge!
vaknar - vakna!
gråter - gråta!

** p.65: Vilka verb finns i imperativ i stycket?

kör! -> kör
spänn! -> spänner
bromsa! -> bromsar
stanna! -> stannar
åk! -> åker
sväng! -> svänger
var! -> är
gör! -> gör
tänk! -> tänker
fortsätt! -> fortsätter

** p.65: Lyssna på bandet.

1. vissla!
2. hosta!
3. stop!
4. sitt ner!
5. knacka i bordet!
6. vissla!
7. vinka!
8. hosta!
9. stop!
10. vinka!
11. hosta!
12. sitt ner!
13. ta fram ett papper!
14. skriv ditt förnamn på pappret!
15. visa det för en kamrat!
16. upprepa tre gångar: Vi läser svenska!
17. pekka på din näsa!
18. pekka på din mun!
19. vissla!
20. tralla lite!
21. vinka!
22. pekka på din näsa!
23. pekka på din lärare!
24. titta ut genom ett fönster!
25. pekka på din lärare!
26. knacka i bordet!
27. tralla!
28. pekka på din mun!
29. ge en penna till en klasskamrat!
30. ta tillbaka pennan!
31. stop!
32. sitt ner!
33. applådera!

** p.66: Imperativ: Ge råd till problemet!

1. Drick en kopp kaffe!
2. Ät ett äpple!
3. Ta en taxi!
4. Köp ett lexikon!
5. Skaffa en karta!
6. Sätt på värmen!
7. Öppna ett fönster!
8. Gå till en tandläkare!
9. Sjung en sång!
10. Ta en magnecyl!

** p.66: Tvättprogram

sortera tvätten i vittvätt, kulörtvätt etc.
stoppa in tvätten
häll i tvättmedel
stäng luckan
slå på strömbrytaren
ställ in rätt program
tryck på startknappen
gör något annat en timme eller så
centrifugera tvätten
ta en kaffepaus
öppna tvättmaskinsluckan
ta ut tvätten
häng upp tvätten på tork
pusta ut
stryk, vik eller mangla
lägg in tvätten i skåp och lådor

** p.68: Possessiva pronomen (och adjektiv)!

1. Din fru är arg.
2. Hans cykel är trasig.
3. Vårt klassrum är stort.
4. Deras vänner är trevliga.
5. Vår lärare är snäll.
6. Er skola är ny.
7. Deras kritik är hård.
8. Ert vardagsrum är ljust.
9. Dina skor är snygga.
10. Mitt arbete är intressant.
11. Din syster är söt.
12. Hennes bror är elak.
13. Min lön är dålig.
14. Hans kunskaper är dåliga.
15. Ditt hus är fint.
16. Mina hundar är arga.
17. Våra klasskamrater är duktiga.
18. Hennes leende är vackert.
19. Era övningar är svåra.
20. Hennes föräldrar är unga.

** p.69: Skriv om texten med ni i stället för du!

Vad gör ni just nu?

Just nu sitter ni (eller ligger eller står) och läser en text i er
lärobok. Ni sitter kanske hemma i er fåtölj eller så är ni i ert
klassrum tillsammans med era klasskamrater. Ni läser kanske tyst,
eller er lärare kanske läser före och ni efter. Era ögon ser texten
och er hjärna tolkar innehållet och ni tänker: "Vilken konstig text!
Den handlar bara om possessiva pronomen!"

** p.73: Svara på frågorna!

1. Ingvar Kamprad föddes i Småland. (föddes -> är född)
2. Han slutade skolan 1941. (slutade -> slutar)
3. Han var dyslektiker. (var -> är)
4. Han arbetade på ett företag som tillverkade monteringsfärdiga hus.
   (arbetade -> arbetar, tillverkade -> tillverkar)
5. Han hade en egen firma. (hade -> har)
6. Han sålde billiga möbler per postorder. (sålde -> säljar)
7. Affärerna gick mycket bra. (gick -> går)
8. Han tryckte massor av kataloger. (tryckte -> trycker)
9. Han delade ut dem gratis till hushållen. (gjorde -> gör, delade -> dela)
10. Ja, det har jag.

Alla preteritumformer i texten:

| preteritum  | presens    |
|-------------+------------|
| var         | är         |
| hade        | har        |
| föddes      | är född    |
| slutade     | slutar     |
| började     | börjar     |
| arbetade    | arbetar    |
| tillverkade | tillverkar |
| sålde       | säljar     |
| tjänade     | tjänar     |
| sparade     | sparar     |
| köpte       | köper      |
| grundade    | grundar    |
| öppnade     | öppnar     |
| tryckte     | trycker    |
| delade      | delar      |
| visade      | visar      |
| lärde       | lärar      |

** p.75: Svara på frågorna.

1. Lissi är en flicka ( -> hennes bil, osv.)
2. Berättelsens "jag" var 18 år gammal.
3. Hon arbetade på Posten halva juni och hela juli.
4. Hon tjänade tillsammans 12 500 kr.
5. Resan startade i Karlskoga i Värmland.
6. De hyrde kanotet. De hade deras själva tält, sovsäckar ock campingkök.
7. De lyssnade på fåglarna, vilade på stranden, lagade mat, spelade flöjt.
8. De lämnade bilen i Karlskoga.

** p.75: Vad hörde personen på bandet? Lyssna och skriv!

En dag i förra veckan satte jag på min bandspelare och spelade en
olika ljud. Efter en stund glömde jag bort bandspelaren. På kvällen
lyssnade jag på bandet, och då hörde jag följande. Jag hörde en person
som hostade. Det var jag. Jag bläddrade tidningen, gick på toaletten,
visslade, öppnade balkongdörren, började laga lunch i köket, skramlade
med kastruller, öppnade och stängde kylskåpet, dukade, åt, diskade,
ringde ett samtal, talade för mig själv, och gick och låg mig på
soffan. Sedan blir det tyst i tag. Sedan hörde jag några mystiska
ljud. Det var jag själv som snarkade. Jag spolade snapp tillbaka,
spelade en lite musik istället.

** p.76: Här är några verb ur texten, i preteritum.

| presens  | preteritum | imperativ |
|----------+------------+-----------|
| slutar   | slutade    | sluta!    |
| är       | var        | var!      |
| arbetar  | arbetade   | arbeta!   |
| sorterar | sorterade  | sortera!  |
| hämtar   | hämtade    | hämta!    |
| städar   | städade    | städa!    |
| spelar   | spelade    | spela!    |
| tjänar   | tjänade    | tjäna!    |
| sparar   | sparade    | spara!    |
| använder | använde    | använd!   |
| åker     | åkte       | åk!       |
| hyr      | hyrde      | hyr!      |
| har      | hade       | ha!       |
| köper    | köpte      | köp!      |
| packar   | packade    | packa!    |
| startar  | startade   | starta!   |
| följar   | följde     | följa!    |
| paddlar  | paddlade   | paddla!   |
| stannar  | stannade   | stanna!   |
| lyssnar  | lyssnade   | lyssna!   |
| vilar    | vilade     | vila!     |
| lagar    | lagade     | laga!     |
| kokar    | kokade     | kok(a)!   |
| grillar  | grillade   | grilla!   |
| somnar   | somnade    | somna!    |
| reser    | reste      | res!      |
| badar    | badade     | bada!     |
| simmar   | simmade    | simma!    |
| fiskar   | fiskade    | fiska!    |
| väntar   | väntade    | vänta!    |

** p.76: En helt vanlig dag

gjorde
steg
duschade, åt, läste
lyssnade, pratade
körde
började
åt
slutade
åkte, köpte
lämnade, var
lagade, åt, dukade
diskade, tittade, rättade
hjälpte, läste
somnade
var

** p.76: Stockholm-Mora med bil

Klockan 7 på morgonen lämnade jag Stockholm. Först körde jag mot
Enköping, och sedan svängde jag in på väg 70 mot Sala. Jag åkte igenom
Sala också, men sedan vände jag och åkte tillbaka ett par kilometer,
till Sala silvergruva. Jag tittade på gruvan och fikade på en
cafeteria och läste tidningen i lugn och ro. Sedan tankade jag och
startade igen. Jag körde raka vägen och passerade Avesta, Borlänge och
Leksand, men då var jag trött, så jag stannade och gymnastiserade lite
och rökte en cigarrett, och sedan körde jag vidare. Klockan två nådde
jag Mora, efter en resa på 35 mil.

** p.79: Man eller en?

Om polisen stoppar en när man kör bil,
måste man visa körkortet. När man är sjuk, bör
man stanna hemma. Ingen tackar en om man går
till jobbet, när man är sjuk.
- Får man röka här?
- Nej, man måste gå ut och röka.
I Sverige går man i pension, när man fyller 65 år.

** p.82: Du har en dotter på 13 år. Vad svarar du henne?

Nej, du får inte titta på det.
Nej, du får inte göra det.
Du behöver inte diska, om du vill inte.
Du får inte stanna upp så längre.
Du måste göra dina läxor varje kväll.
Nej, du får inte börja det.
Nej, du måste sova hemma.
Nej, du måste inte göra det.
Nej, du får stanna hemma, om du vill.

** p.83: Skriv om meningarna!

1. Jag kan spela piano.
2. Vi måste studera svenska.
3. Hon får inte röka.
4. Hon behöver inte vakna tidigt.
5. Jag måste vänta på Cecilia.
6. Kan du tala franska?
7. Jag vill låna telefonen.
8. Får du gå ut ikväll?
9. Jag kan inte somna.
10. Behöver du inte stiga upp tidigt?
11. Får du och din bror röka?
12. Jag vill vara ensam.

** p.83: Hur bör en lärare vara?

En lärare bör vara snäll, intelligent, lugn, intresserad.
En läkare bör vara renlig, noggrann, snabb.
En journalist bör vara rättvis, uppriktig, beslutsam, nyfiken.
En präst bör vara varm, förstående, glad.
En chef bör vara duktig, stolt, ekonomisk.
En förälder bör vara bestämd, rättvis, varm, sparsam.
En student bör vara flitig, morgonpigg, punktlig, nyfiken.


* Övningar del 1

** 1
1. frågar
2. svarar
3. kommer
4. talar
5. skriver
6. bor
7. arbetar
8. har
9. presenterar
10. följer
11. undervisar
12. tror

** 2A
1. Vad
2. Var
3. Varifrån
4. Var
5. Vad
6. Vad
7. Var
8. Vad

** 2B
1. Vad heter hon?
2. Vad läser hon?
3. Var arbetar du?
4. Vad skriver han?
5. Varifrån kommer du?
6. Var bor du nu?
7. Vad läser han för språk?
8. Vad studerar hon mer?

** 2C

1. Jag heter Anna. Anna heter jag.
2. Många talar lite engelska. Lite engelska talar många.
3. Hon arbetar i Japan. I Japan arbetar hon.
4. Han läser en bok. En bok läser han.
5. Han har tre barn. Tre barn har han.
6. Jag studerar här. Här studerar jag.

** 3

1. Bor du här?
2. Kommer du från Bonn?
3. Heter han Bob?
4. Läser hon tyska?
5. Är de gifta?
6. Arbetar ni här?
7. Talar alla svenska?
8. Är hon lärare?
9. Har de barn?
10. Är han förlovad?

** 4

1. Han bor nu i Polen. (... i Polen nu?) I Polen bor han nu. Nu bor han i Polen.
2. Alla barn läser engelska i Sverige. I Sverige läser alla barn engelska.
   Engelska läser alla barn i Sverige.
3. Anna studerar svenska på universitetet. Svenska studerar Anna på universitetet.
   På universitetet studerar Anna svenska.
4. De undervisar i spanska här. I spanska undervisar de här. Här undervisar de i spanska.

** 5

1. går, gapar, god, gul, gott, gata, gång
   ger, gärna, gör, gift, gick
2. kall, kår, konstig, kul, kastar, ko
   köper, kyss, kikar, kär, kyrka
3. ska, sko, skulle, skata, skål, skola
   sker, skön, sked, skär, skylt

** 6

A.
hEter vIdare tAlar studErar lÄrare dElar bOr
lÄser stAvar vokAl frÅgar bArn
skOla universitEt sprÅk

B.
koMMer naMn yRke gäSt konsonaNt doTTer
sveNska giFt förfaTTare gaMMal plaTs eNGelska

C.
ingen

** 7

född tolk namn roll svenska jobbar mystik kort
gift kommer tyvärr ligger passar yrke främre gäst

** 8

1. en penna
2. en väska
3. en kamera
4. En hund
5. ett suddgummi
6. en fågel (ett flygplan)
7. en pistol
8. ett fönster
9. en stol
10. en bok
11. en skåp
12. en pärm ??? (en bord)
13. ett universitet
14. en skruvmejsel
15. ett måttband
16. en hammare

** 9

1. sex prick (på morgonen)
2. halv åtta (på kvällen)
3. tio över två (på eftermiddagen)
4. kvart över ett (på dagen)
5. tjugo i tio (på förmiddagen)
6. fem prick (på kvällen)
7. halv fyra (på eftermiddagen)
8. fem i ett (på dagen)
9. tio i nio (på morgonen)
10. halv sex (på kvällen)
11. kvart i fyra (på eftermiddagen)
12. halv fem (på morgonen)
13. halv två (på eftermiddagen)
14. fem över sex (på morgonen)
15. tio över sju (på kvällen)
16. halv tio (på kvällen)

** 10

1. Han går hemifrån klockan sju.
   Hemifrån går han klockan sju.
   Klockan sju går han hemifrån.
   Går han hemifrån klockan sju?
2. De äter frukost kvart i sex.
   Frukost äter de kvart i sex.
   Kvart i sex äter de frukost.
   Äter de frukost kvart i sex?
3. Vad äter de till frukost?
4. Hon vaknar halv åtta på morgonen.
   Halv åtta vaknar hon på morgonen.
   På morgonen vaknar hon halv åtta.
   Vaknar hon halv åtta på morgonen?
5. När har du lunch?
6. Han är inte lärare.
   Inte är han lärare.
   Lärare är han inte.
   Är han inte lärare?
7. De går på disko klockan elva.
   På disko går de klockan elva.
   Klockan elva går de på disko.
   Går de på disko klockan elva?
8. Han äter lite filmjölk klockan tolv.
   Lite filmjölk äter han klockan tolv.
   Klockan tolv äter han lite filmjölk.
   Äter han lite filmjölk klockan tolv?
9. Var bor du nu?

** 11

1. en arbetare
2. en författare
3. en talare
4. en läsare
5. en väljare
6. en städare
7. en tittare
8. en lyssnare

** 12

1. en kurs
2. ett språk
3. en plats
4. en lucka
5. ett suddgummi
6. ett förnamn
7. en penna
8. ett verb
9. en vägg
10. ett klockslag
11. en radio
12. en tanke

** 13

1. Hur mycket är klockan?
2. Jag har en klocka.
3. Vi tar en paus nu.
4. Vad gör du efter pausen?
5. Hon har ett barn.
6. Ser du barnet där borta?
7. Man skriver med en penna.
8. Den här pennan är bra.
9. Jag läser svenska på en kvällskurs.
10. När börjar kursen?

** 14

1. Elin läser engelska.
2. Jag har en dotter.
3. Katarina är lärare.
4. När äter vi middag?
5. Olle skriver en övning.
6. Marie skriver ofta brev.
7. Är Kajsa polis?
8. Tycker du om filmjölk?
9. Har du paus nu?
10. Lyssnar ni på musik?
11. Äter han bara ett äpple till lunch?

** 15

1. trött
2. dag
3. fråga
4. från
5. somnar
6. elev
7. börjar
8. lyssnar
9. konsonant
10. gift
11. inga
12. mycket
13. pojke
14. kommer
15. kväll

** 16

1. Jag sitter och skriver.
2. Jag ligger och läser.
3. Jag håller på och diskar.
4. Jag står och duschar, förstås!
5. Jag låller på och lagar mat.
6. Jag sitter och lyssnar på musik.

** 17

1. nittioåtta
2. trehundrafyra
3. sjuhundratrettio
4. tjugosex
5. sjutusenåttahundratjugonio
6. åttiofemtusentrehundrafemtiosju
7. etthundratvåtusenfyrahundraåttiotre
8. sjuhundrasjuttiosjutusenåttiohundratjugotvå

** 18

1. Hon pluggar aldrig.
2. De arbetar inte just nu.
3. Hunden är alltid hungrig.
4. Han är inte hemma.
5. Barnet vaknar sällan på natten.
6. Patrik tittar ofta på TV.

** 19A

1. På kvällen är hon ofta pigg.
2. Klockan ett på natten sover jag nästan alltid gott.
3. Till Malmö åker jag sällan.
4. I vardagsrummet finns ofta en soffa.

** 19B

1. Varför arbetar hon sällan på förmiddagen?
2. Varför lyssnar de nästan alltid på radio?
3. Varför kommer du aldrig hem?
4. Är morfar ofta trött?
5. Dricker Olle alltid juice på morgonen?
6. Går du ofta på konsert?
7. Röker ni aldrig i sovrummet?
8. Ofta skriver hon på datorn?

** 20

1. 616 90 : postnummer
2. Roger : förnamn
3. blond : hårfärg
4. Karlsson : efternamn
5. 011-123625 : telefonnummer
6. Åby : bostadsort
7. 450224-2219 : personnummer
8. Solvägen 3 : gatuadress
9. fotograf : yrke
10. 182 cm : längd
11. gift : civilstånd
12. 9562 : portkod

** 21

1. ett födelseår
2. en hårfärg
3. en ordföljd
4. ett efternamn
5. ett klassrum
6. en filmrulle
7. ett telefonsamtal
8. ett skonummer
9. en portkod
10. en popgrupp

** 22

Skriv alla verb som har ett långt konsonantljud!

duSCHar daMMsuger viLL daNsar lySSnar riNger stiCKar reGnar diSkar

** 23

1. städa -> städar
2. stryk -> stryker
3. betala -> betalar
4. gå -> går
5. tvätta -> tvättar
6. sy -> syr
7. dammsug -> dammsuger
8. sov -> sover
9. diskutera -> diskuterar
10. ha -> har
11. åk -> åker
12. se -> ser
13. sjung -> sjunger
14. älska -> älskar
15. samla -> samlar
16. sitt -> sitter

** 24

1. Det är Johans piano.
2. Det är Monas bok.
3. Det är Kalles katt.
4. Det är mannens pass.
5. Det är Margaretas dator.
6. Det är sonens hund.
7. Det är kvinnans yrke.
8. Det är Lars dammsugare.
9. Lenas son heter David.
10. Elisabets och Åkes dotter heter Lotta.
11. Sveriges huvudstad heter Stockholm.

** 25

1. Det kallas Norden.
2. Det är avlångt.
3. Då skiner solen tjugofyra timmar.
4. Då är det mörkt och kallt.
5. Den är varm.
6. Där bor det nästan nio miljoner människor.
7. Det heter samiska.

** 26A

1. Han heter Carl XVI Gustav.
2. Hon heter Silvia.
3. Hon kommer från Tyskland.
4. Hon växte upp i Brasilien.
5. De har tre barn.
6. Den heter Bernadotte.
7. Den kommer ursprungligen från Frankrike.

** 26B

1. Oscar den andre
2. Fredrik den förste
3. Gustav den andre Adolf
4. Gustav den tredje
5. Gustav den femte
6. Karl den tionde Gustav
7. Karl den elfte
8. Karl den tolfte
9. Erik den fjortonde

** 27

1. Jag är inte intresserad av svensk musik.
2. Varför läser du aldrig romantiska böcker?
3. Hon skriver ofta till sin brevvän i Brasilien.
4. Det är alltid mycket folk på Stockholms Central.
5. Min man betalar inte räkningarna.
6. Jag träffar ofta min kusin på bussen.
7. Sven äter sällan morötter.

** 28

1. Det är en sjö.
2. Det är en ö.
3. Det är ett landskap.
4. Det är ett landskap.
5. Det är en huvudstad.
6. Det är en ö.
7. Det är en stad.
8. Det är en sjö.
9. Det är ett landskap.
10. Det är en stad.

** 29

1. ett barn
2. en fråga
3. ett fundament
4. en väska
5. en författare
6. ett kapitel
7. en konsonant
8. ett frimärke
9. en plats
10. ett språk
11. ett klockslag
12. ett verb
13. en vokal
14. en övning
15. en del
16. ett pronomen
17. ett diskotek
18. en kurs
19. en lucka
20. ett ord
21. en mening
22. ett svar
23. ett namn
24. en elev
25. en artikel
26. en vinter
27. en fröken
28. en teater

** 30

1. + plus
2. m^2 kvadratmeter
3. . punkt
4. , komma
5. = är lika med
6. : kolon
7. § paragraf
8. % procent

** 31

1. Kerstin undervisar i svenska fem dagar i veckan.
2. Familjen Svensson äter mat tre gånger om dagen.
3. Två gånger i månaden åker Erik till Falun.
4. Hur många gånger om året tar Max semester?
5. Mona röker två cigarretter i timmen.
6. Adam städar en halvtimme om dagen.
7. En gång i veckan går familjen Bergman i kyrkan.
8. Tjänar du mer än 150 000 kr om året?
9. Ja, jag tjänar 14 500 kr i månaden.

** 32

A:

| en         | ett         |
|------------+-------------|
| promenad   | bibliotek   |
| garderob   | universitet |
| restaurang | apotek      |
| toalett    | kontor      |
| cigarrett  |             |
| affär      |             |
| frisör     |             |
| fabrik     |             |

B: en-orden: markerar plural med -er.
C: ett-orden: markerar inte plural.

** 33

Motsatsen:

1. alltid - aldrig
2. hemma - borta
3. klassisk - modern
4. sommar - vinter
5. dag - natt
6. gumma - gubbe
7. ofta - sällan
8. mätt - hungrig
9. ledig - upptagen
10. kvinna - man
11. höger - vänster
12. liten - stor

** 34A

1. Sara hälsar på mig idag.
2. Peter fyller i rätt ord.
3. Tittar han ut genom fönstret?
4. Kommer tåget in nu?
5. Hur står det till?
6. Hur dags stiger du upp?
7. Varje dag delar Pernilla ut tidningar.
8. Ikväll arbetar jag över.
9. Hjälper du till nu?
10. Snön lyser upp vintermörkret.
11. När byter du om?
12. De åker runt i staden.

** 34B

1. De går ofta in till mig.
2. Kopplar du aldrig av?
3. Kommer de inte in?
4. Varför hjälper du inte till?
5. Varför hälsar du aldrig på mig?
6. Lunchen hoppar jag aldrig över.
7. Före nio stiger han sällan upp.
8. Arbetar du aldrig över?
9. Hon hälsar ofta på sin pappa.
10. Popmusik tycker jag inte om.

** 35

1. ett rum
2. ett arbete
3. en vecka
4. en uppgift
5. en pappa
6. en roll
7. en expedit
8. en tolk
9. ett yrke
10. en dialog
11. ett bord
12. en författare
13. en intervju
14. en kyrka
15. en kamera
16. ett resultat
17. en pistol
18. en skata
19. en snickare
20. ett stativ

** 36

1. en golvlampa -or
2. en bokhylla -or
3. ett studenthem =
4. en varmrätt -er
5. en fritid =
6. en järnmalm -er
7. en sportavdelning -ar
8. ett skonummer =

** 37

1. en fotograf -er
2. en fiskare =
3. en expedit -er
4. en snickare =
5. en student -er
6. en bonde, bönder | en jordbrukare =
7. en guldsmed -er
8. en tolk -ar

** 38

1. Tavlan hänger på väggen i rummet.
2. Det finns inte så många bönder i Sverige.
3. Hon arbetar som expedit på ett varuhus.
4. Stjärnorna lyser på himlen.
5. Ordet slutar på en vokal.
6. Tidningen kommer ut en gång i veckan.
7. 15% av Sveriges befolkning bor på landet.
8. 48% av befolkningen bor i småhus.
9. En svensk villa är i genomsnitt 123 m^2.

** 39

|  1 | en pärla     | pärlan     | pärlor    | pärlorna    |
|  2 | en diamant   | diamanten  | diamanter | diamanterna |
|  3 | ett halsband | halsbandet | halsband  | halsbanden  |
|  4 | en högtalare | högtalaren | högtalare | högtalarna  |
|  5 | ett sällskap | sällskapet | sällskap  | sällskapen  |
|  6 | ett piano    | pianot     | pianon    | pianona     |
|  7 | en affisch   | affischen  | affischer | affischerna |
|  8 | en fisk      | fisken     | fiskar    | fiskarna    |
|  9 | ett yrke     | yrket      | yrken     | yrkena      |
| 10 | en frukost   | frukosten  | frukostar | frukostarna |
| 11 | ett djur     | djuret     | djur      | djuren      |
| 12 | en ko        | kon        | kor       | korna       |
| 13 | en stjärna   | stjärnan   | stjärnor  | stjärnorna  |
| 14 | ett jordbruk | jordbruket | jordbruk  | jordbruken  |
| 15 | en dikt      | dikten     | dikter    | dikterna    |
| 16 | ett råd      | rådet      | råd       | råden       |
| 17 | en stol      | stolen     | stolar    | stolarna    |
| 18 | ett verb     | verbet     | verb      | verben      |
| 19 | en stuga     | stugan     | stugor    | stugorna    |
| 20 | ett uttryck  | uttrycket  | uttryck   | uttrycken   |

** 40

1. Var har du böckerna? Jag har de i bokhyllan.
2. Vad är klockan? Den är kvart i tio.
3. När kommer bussen? Den kommer snart.
4. Var ställer vi skåpet? Det ställer vi här.
5. Tycker du om halsbandet? Ja, det är vackert.
6. Skriver du upp frågorna? Ja, dem skriver jag upp på ett papper.

** 41

1. henne
2. mig
3. honom
4. oss
5. mig, honom
6. oss
7. er
8. dig, honom
9. dig, dem

** 42

1. åker
2. vill
3. älskar
4. allting
5. naturligtvis
6. bonde
7. pratar
8. villa
9. många, mycket

** 43

1. en bok
2. en mo(de)r
3. en bonde
4. en son
5. en dotter
6. en stad
7. en fa(de)r
8. en tand
9. en natt
10. en man
11. en morgen
12. en bro(de)r

** 44

1. gult, gul, gula, gul
2. fina, fin, fint, fina
3. intressant, intressant, intressanta
4. glad, glada, glatt
5. nya, nytt, ny, nytt
6. liten, små, litet, små

** 45

1. vita
2. varmt
3. internationell
4. små
5. klok
6. unga
7. trött
8. tomt
9. svåra

** 46

| mor     | son      | hon      | honom  |
|---------+----------+----------+--------|
| bor     |          |          |        |
|         |          | ett kort |        |
|         |          |          | och    |
|         | rosa     |          |        |
|         |          |          | folk   |
| person  |          |          |        |
|         |          | bonde    |        |
| sko     |          |          |        |
|         |          | tom      |        |
|         | brosch   |          |        |
|         |          |          | korv   |
|         |          |          | idrott |
|         |          |          | blond  |
| lektion |          |          |        |
|         | förlovad |          |        |
| olika   |          |          |        |
|         |          |          | kommer |
| stor    |          |          |        |
|         | telefon  |          |        |
|         |          | tobak    |        |
|         |          |          | tolk   |
|         |          |          | dotter |
|         | dialog   |          |        |
| ogift   |          |          |        |

** 47

1. ung, ungt, unga
2. långt, långa, lång
3. mörka, mörk, mörkt
4. snäll, snälla, snällt
5. dum, dumt, dumma
6. gamla, gammalt, gammal

** 48

1. olik
2. omodern
3. ovälkommen
4. orädd
5. ohjälpsam
6. oprofessionell
7. ointressant
8. otrevlig
9. oregelbunden
10. orätt
11. orättvis
12. obestämd

** 49

1. mat - hatt, lat
2. gardin - fin
3. kamma - samma
4. klocka - plocka
5. retar - letar
6. från - son, lång
7. hyra - fyra
8. skor - tror
9. räcka - väcka
10. sol - fiol
11. herr - tyvärr
12. fjäll - speciell
13. sula - kula
14. tom - from
15. än - en
16. plus - buss

** 50

1. Ja, det gör jag. Nej, det gör jag inte.
2. Jo, det är jag. Nej, det är jag inte.
3. Ja, det har jag. Nej, det har jag inte.
4. Jo, det gör jag. Nej, det gör jag inte.
5. Ja, det är jag. Nej, det är jag inte.
6. Ja, det gör det. Nej, det gör det inte.
7. Jo, det har jag. Nej, det har jag inte.
8. Ja, det gör jag. Nej, det gör jag inte.

** 51

1. Elefanten är ett stort djur. Den finns i Afrika och Indien och
   har en snabel istället för en nos.

2. Vargen är ett rovdjur. Den finns i norra Sverige och ser
   nästan ut som en hund.

3. Hästen är ett husdjur. Man kan rida på den, och den gnäggar
   ibland. Den bor i ett stall.

4. Svinen/Grisen är ett annat husdjur. Den grymtar och bor i en stia.

5. Ibland säger man att räven är listig. Den har rödbrun päls och
   finns i stora delar av Sverige.

6. Sebran är ett randigt djur, ränderna går aldrig ur. Den lever
   i Afrika.

7. Lejonet är Afrikas största kattdjur.

8. Lodjuret är ett vilt kattdjur. Det finns i Sverige.

9. Björnen ligger i ide på vintern. Den brummar och finns i norra
   och mellersta Sverige.

10. Apan är en vig släkting till människan, och den finns vild i
   både Afrika, Sydamerika och Asien.

11. Åsnan liknar en häst. Man säger att den är bäde dum och envis.

12. Myran är en liten, flitig insekt. Den bor i en stack.

13. Hönsen/Tuppen är en tamfågel. Den gal tidigt på morgnarna.

** 52A

1. ett arbete -> -n
2. ett tal -> =
3. en syn -> -er
4. en fråga -> -or
5. en gråt -> 0
6. en sömn -> 0
7. ett liv -> =
8. ett byte -> -n
9. ett köp -> =
10. en resa -> -or
11. en dans -> -er
12. ett regn -> 0
13. en sång -> -er
14. en idrott -> -er
15. en import -> -er
16. en dryck -> -er

** 52B

1. ett arbete -> arbetar
2. ett tal -> talar
3. en syn -> ser
4. en fråga -> frågar
5. en gråt -> gråter
6. en sömn -> somnar
7. ett liv -> lever
8. ett byte -> byter
9. ett köp -> köper
10. en resa -> reser
11. en dans -> dansar
12. ett regn -> regnar
13. en sång -> sjunger
14. en idrott -> idrottar
15. en import -> importerar
16. en dryck -> dricker

** 53

ställer, hör, menar, säger, svär, dirigerar, hyr, byter,
gråter, går, bär, äter, skär, agerar, tar, gör

** 54

A:

1. böjning
2. skrivning
3. tryckning
4. strykning
5. stängning
6. skakning
7. läsning
8. rynkning
9. körning
10. rökning
11. viftning
12. klippning

B: en

C: -ar

** 55A

1. vårt problem, vår dotter, våra söner
2. din husvagn, dina äpplen, ditt rum
3. er soffa, ert arbete, era böcker
4. mitt kök, mina vänner, min bil

** 55B

1. Problemet är vårt. Dottern är vår. Sönerna är våra.
2. Husvagnen är din. Äpplena är dina. Rummet är ditt.
3. Soffan är er. Arbetet är ert. Böckerna är era.
4. Köket är mitt. Vännerna är mina. Bilen är min.

** 56

1. Är det hans piano?
2. Det är vår katt.
3. Det är deras dator.
4. Hör ni min hund?
5. Trivs du med ditt arbete?
6. Använder ni er dammsugare?
7. Hennes son heter David.
8. Deras (hennes och hans) dotter heter Lotta.
9. Vår (min mans och min) villa ligger på Brogatan.
10. Jag tycker om ert (ditt och din mans) hus.

** 57

klassrum, medelåldern, samtal, tågluffar, tandläkare, ryggsäck,
kaffepaus, tvättmaskin, badrum

** 58A

1. Luleå är en stad, som ligger i norra Sverige.
2. Lisa har två morbröder, som är lärare.
3. Ser du fågeln, som sitter där i trädet?
4. Det här är min syster, som bor i USA nu.
5. Min moster är gift med en trevlig man, som kommer frå Uganda.
6. Snart kommer sommaren, som är så varm och skön.
7. Där springer katten, som har sju ungar.
8. Jag älskar en kvinna, som är mycket intelligent.

** 58B

1. kusiner
2. farbröder
3. moster
4. farmor
5. kusin
6. farfar
7. farbror
8. morfar

** 59

cyklade, skickade, mådde, reste, jämförde, svarade, köpte, trodde,
körde, sydde, tolkade, bodde, stängde, tryckte, klappade, bytte

** 60

1. Min dotter började skolan i höstas.
2. Vad gjorde du i torsdags?
3. Det var kallt i morse.
4. Regnade det mycket i somras?
5. Olle lärde sig åka skidor i vintras.
6. Den här jackan köpte jag i lördags.
7. I morse steg jag upp tidigt.
8. Vi träffade varandra i våras.
9. Vi var på konsert i onsdags kväll.
10. Åh, vad jag var trött i måndags morse!

** 61

1. Kommer du nu? Lektion börjar ju om tio minuter.
2. Jag blev sjuk för tre dagar sedan.
3. Han föddes för tio år sedan.
4. Min bror kommer till Sverige om sju månader.
5. Din chef ringde för två timmar sedan.
6. Kursen slutade för en vecka sedan.
7. Vi äter om en kvart.

** 62

1. hade, har
2. mådde, mår
3. åker, åker
4. bakar, bakade
5. följde, följer
6. drömde, drömde
7. simmar, simmade

** 63A

1. barnlösa
2. tanklös
3. ärmlös
4. kraftlös

5. arbetslösa
6. ansvarslösa
7. svarslös

** 63B

1. arbetsfri
2. barnfria
3. ogräsfri
4. alkoholfritt

** 64

1. man, man
2. man, man
3. ens
4. man, en

** 65

1. kök
2. tjock
3. känd
4. kilo
5. tjugo
6. kylskåp
7. köper
8. tjuv
9. kyckling
10. kött
11. tjatar
12. kör

** 66

1. När ska vi åka?
2. Jag vill inte städa.
3. Nu måste du sova.
4. Får han komma?
5. Farfar kan inte laga mat.
6. Kan ni komma hit ikväll?
7. Måste barnen tvätta sig nu?
8. Brukar du aldrig snickra?
9. Du får naturligtvis bestämma.
10. På torsdag vill jag gärna komma.
11. Du måste köpa potatis idag.
12. Man bör alltid äta frukost.

** 67

1. får, få
2. tänker, tänka
3. köpte, köpa
4. använda, använder
5. städa, städade

** 68

armé brandstation fängelse ekonomisk
räkor sträng uppriktig älskar

1. ett kilo = tio hekto
2. göra värnplikten = göra lumpen
3. Det kostar inget. = Det är gratis.
4. Jag trivs inte. = Jag vantrivs.
5. restaurang = krog
6. inte krig = fred
7. Gevär och pistoler är vapen.
8. sätter ihop = monterar
9. Den som handlar i en affär är kund där.
10. Han kommer i tid. = Han är punktlig.
11. fackföreningen = facket
12. Hon har inget arbete. = Hon är arbetslös.
13. I en gruva bryter man malm ur berget.

** 69

1.
2. att
3. att
4.
5.
6. att
7. att
8.
9.
10.
11. att
12.

** 70

A:

1. preposition
2. sju
3. skidor
4. själv
5. skild
6. instruktion
7. skiner
8. sjö
9. sjukhus
10. maskin
11. lektion
12. sjunger

B:

1. schema
2. skjorta
3. broschyr
4. stjärna

C:

1. journalist
2. dirigerar
3. chef
4. regissör

** 71

1. nyfiken
2. allmän
3. tungt
4. uppriktig
5. flitig, noggrann
6. aktuella
7. vemodig
8. stolt
9. blyg
10. historisk
11. hänsynsfull
12. beslutsam

** 72

A:

1. reparation
2. information
3. demonstration
4. organisation
5. kommunikation
6. produktion
7. repetition
8. diskussion

B: en

C: -er


PP.18/30(FACIT)
